[tool.poetry]
name = "cgap-pipeline-utils"
version = "1.6.0.dev"
description = "Repository implementing utilities for deploying pipelines that implement the CGAP-Pipeline specification."
authors = ["CGAP Team"]
license = "MIT"
repository = 'https://github.com/dbmi-bgm/cgap-pipeline-utils'
classifiers = [
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3'
]
packages = [
    { include="pipeline_utils" }
]


[tool.poetry.dependencies]
python = ">=3.6.1,<3.10"
dcicutils = "^3.2.0"
magma-suite = "^0.2.1"
boto3 = "^1.20.15"
awscli = "^1.22.15"


[tool.poetry.scripts]
pipeline_utils = "pipeline_utils.__main__:main"


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
