# GitHub Actions workflow that runs on a cron schedule.

name: Weekly CI Tests

on:
  schedule:
    # run at 6am UTC on Mondays
    - cron: '0 6 * * 1'

jobs:
  # Weekly testing to catch links that stop working for some reason.
  doc_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Check links in docs using tox
      run: |
        tox -e linkcheck
