[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127

[tool.coverage.report]
exclude_lines = [
    'if __name__ == "__main__":',
]
fail_under = 100

[tool.coverage.run]
branch = true
omit = [
    ".venv/*",
]

[tool.isort]
line_length = 127
case_sensitive = true
profile = "black"

[tool.mypy]
show_error_codes = true
strict = true

[tool.poetry]
name = "fem-kit"
version = "2022.0"
description = "Geoemtry modification and modeling tools to create and publish an industry strength numerical solver into an optimization chain, which can handle real-time data. "
authors = [
    "Tamás Orosz <orosz.tamas@yahoo.com>"
]
license = "Apache-2.0"
packages = [
    { include = "src" },
    { include = "src/**/*.py" },
]
readme = "README.md"
homepage = "https://github.com/tamasorosz/fem-kit"
repository = "https://github.com/tamasorosz/fem-kit"
keywords = ["scientific", "engineering", "fem", "transformers", 'optimization', "digital twin"]


[tool.poetry.dependencies]
python = "^3.6"
typer = "*"

[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
gitlint = "*"
isort = "*"
language-formatters-pre-commit-hooks = "*"
mutmut = "*"
mypy = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
pytest-randomly = "*"
typed-ast = "*"

[tool.pylint.FORMAT]
max-line-length = 127

[tool.pylint.MASTER]
disable = [
    "bad-continuation",
    "duplicate-code",
    "invalid-name",
    "missing-docstring",
    "too-few-public-methods",
]
