version: '3.7'

services:

  car.ftp:
    container_name: car.ftp
    image: ghcr.io/qtc-de/container-arsenal/ftp:1.0.0
    build: .
    environment:
      FTP_PORT: ${car_ftp_port}
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_user_folder}:/ftp/user
      - ${car_anon_folder}:/ftp/anon
      - ./scripts/start.sh:/scripts/start.sh
      - ./config/vsftpd.conf:/etc/vsftpd/vsftpd.conf
    network_mode: "host"
