name: CI

on:
  push:

jobs:
  build-wheel:
    name: "🏗️ Python wheel"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          - windows-latest
        python:
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip build twine
      - name: "🏗️ Build Python wheel"
        run: python -m build
      - name: "🧪 Check package bundles"
        run: twine check dist/*
      - name: "📤 Upload Python wheel"
        uses: actions/upload-artifact@v2
        with:
          path: dist/*
          name: Wheels (${{ matrix.python }}, ${{ matrix.os }})
  code-format:
    name: "🔍 Python code format"
    needs:
      - build-wheel
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        python:
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
      - name: "🔍 Check Python code format"
        run: flake8 ir_axioms/ tests/
  lint:
    name: "🔍 Python Lint"
    needs:
      - build-wheel
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        python:
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
      - name: "🔍 Lint Python code"
        run: pylint -E ir_axioms tests.unit --ignore-paths=^ir_axioms.backend
  lint-backend:
    name: "🔍 Python Lint backend"
    needs:
      - build-wheel
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        python:
          - 3.8
          - 3.9
        backend:
          - pyserini
          - pyterrier
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
          pip install .[${{ matrix.backend }}]
      - name: "🧰 Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: "🔍 Lint Python code"
        run: pylint -E ir_axioms.backend.${{ matrix.backend }} tests.integration.${{ matrix.backend }}
  unit-tests:
    name: "🧪 Python unit tests"
    needs:
      - build-wheel
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        python:
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
      - name: "🧪 Test Python code"
        run: pytest --cov=./ --cov-report=xml ir_axioms/ tests/unit/ --ignore=ir_axioms/backend/
  integration-tests:
    name: "🧪 Python integration tests"
    needs:
      - build-wheel
      - unit-tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        python:
          - 3.8
          - 3.9
        backend:
          - pyserini
          - pyterrier
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
          pip install .[${{ matrix.backend }}]
      - name: "🧰 Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: "🧪 Test Python code"
        run: pytest --cov=./ --cov-report=xml --cov-append tests/integration/${{ matrix.backend }}/
  coverage:
    name: "📤 Publish test coverage"
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: "📤 Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: "🚀 Publish Python package"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - build-wheel
      - code-format
      - lint
      - lint-backend
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip build
          pip install -e .
      - name: "🏗️ Build Python wheel"
        run: python -m build
      - name: "🚀 Publish Python package"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  release:
    name: "🚀 Create GitHub release"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - build-wheel
      - code-format
      - lint
      - lint-backend
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🏷️ Get version tag"
        id: get-version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: "🧰 Install Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: setup.cfg
      - name: "🧰 Install dependencies"
        run: |
          python -m pip install --upgrade pip build
          pip install -e .
      - name: "🏗️ Build Python wheel"
        run: python -m build
      - name: "🚀 Create GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get-version.outputs.tag }}
          files: dist/*
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true