
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T11:39:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d37065716457147e01d6fe1b1d83efcc81c17617",
 "version": "0.7.1.post.dev547"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
