[tool.poetry]
name = "plotly-resampler"  # Do not forget to update the __init__.py __version__ variable
version = "0.5.0"
description = "Visualizing large time series with plotly"
authors = ["Jonas Van Der Donckt", "Jeroen Van Der Donckt", "Emiel Deprost"]
readme = "README.md"
repository = "https://github.com/predict-idlab/plotly-resampler"
documentation = "https://predict-idlab.github.io/plotly-resampler"
keywords = ["time-series", "visualization", "resampling", "plotly", "plotly-dash"]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
jupyter-dash = ">=0.4.2"
plotly = "^5.6.0"
dash = "^2.2.0"
lttbc = "0.2.0"
orjson = "^3.6.7"
pandas = "^1.3.5"
trace-updater = ">=0.0.8"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.2.0"
numpy = "^1.21.2"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = {version = "^21.11b1", allow-prereleases = true}
selenium = "^4.1.0"
pytest-selenium = "^2.0.1"
webdriver-manager = "^3.5.2"
pyarrow = "^6.0.1"
selenium-wire = "^4.5.6"
pyfunctional = "^1.4.3"
dash-bootstrap-components = "^1.0.3"
Sphinx = "^4.4.0"
pydata-sphinx-theme = "^0.8.0"
sphinx-autodoc-typehints = "^1.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
