
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T20:05:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "62878fa9328de06eeac336a63db6f5bc689b5a39",
 "version": "0.0.77.post0.dev43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
