VERSION_YEAR = 2022
VERSION_MONTH = int('04')
VERSION_DAY = int('29')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202204290528
version_date = '2022/04/29 05:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
