[tool.isort]
profile = "black"
line_length = 100

[tool.black]
target-version = ['py310']
line-length = 100
exclude = 'schema/'

[tool.pylint]

	[tool.pylint.FORMAT]
	max-line-length = 100


[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "strict"
reportMissingTypeStubs = false


[tool.mypy]
python_version = "3.10"
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
