
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-27T19:56:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c935a02c820312d23569ff270a50ef91d11c542e",
 "version": "0.0.77.post0.dev76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
