
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T16:22:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6138e981b51ffd59e9ff889fb91a11625a2cb28c",
 "version": "v2.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
