[tool.poetry]
name = "django-generic-tasks"
version = "0.2.3"
description = ""
authors = ["Jiayu Yi <yijiayu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django-ninja = "^0.17.0"
Django = "^4.0.4"
google-auth = "^2.6.6"
google-cloud-tasks = "^2.8.1"
CacheControl = "^0.12.11"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
