name: Notebook tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test notebooks with nbmake
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]'
      - name: Test notebooks
        run: |
          pytest --nbmake --nbmake-timeout=3000  examples/*ipynb