[tool.mypy]
python_version = 3.7
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.pycln]
all = true


[tool.poetry]
name = "tootbot"
version = "5.0.0"
description = "A Python bot that looks up posts from specified subreddits and automatically posts them on Mastodon"
authors = ["marvin8 <marvin8@tuta.io>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://codeberg.org/MarvinsMastodonTools/tootbot"
repository = "https://codeberg.org/MarvinsMastodonTools/tootbot"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
]

[tool.poetry.urls]
"Changelog" = "https://codeberg.org/MarvinsMastodonTools/tootbot/src/branch/main/CHANGELOG.md"
"Wiki" = "https://codeberg.org/MarvinsMastodonTools/tootbot/wiki"
"Bug Tracker" = "https://codeberg.org/MarvinsMastodonTools/tootbot/issues"

[tool.poetry.scripts]
tootbot = "tootbot.command_line:start"
tootbot_create_config = "tootbot.create_config:create"
tootbot_cache_2_sqlite = "tootbot.migrations:move_2_sqlite"

[tool.poetry.dependencies]
python = "^3.7"
gfycat = "^0.2.2"
imgurpython = "^1.1.7"
"Mastodon.py" = "^1.5.1"
Pillow = "^9.0.1"
praw = "^7.5.0"
arrow = "^1.2.2"
coloredlogs = "^15.0.1"
beautifulsoup4 = "^4.10.0"
httpx = "^0.22.0"
rich = "^12.0.0"
alive-progress = "^2.3.1"
elapsed = "^2020.12.3"
python-magic = "^0.4.25"
lxml = "^4.8.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pylint = "^2.12.2"
flake8 = "^4.0.1"
black = "^22.1.0"
dlint = "^0.12.0"
flake8-eradicate = "^1.2.0"
mypy = "^0.950"
pytest-testmon = "^1.3.1"
pytest-cov = "^3.0.0"
pytest = "^7.0.1"
pytest-mock = "^3.7.0"
flake8-bugbear = "^22.1.11"
pep8-naming = "^0.12.1"
flake8-black = "^0.3.2"
flake8-import-order = "^0.18.1"
bandit = "^1.7.4"
safety = "^1.10.3"
flake8-annotations = "^2.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
