
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-29T09:19:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0be21c54ac434796e9806ec13552e98eb5f89c4",
 "version": "v0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
