# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining/v1/entailment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'arg_services/mining/v1/entailment.proto\x12\x16\x61rg_services.mining.v1\"_\n\x11\x45ntailmentRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language\x12\x18\n\x07premise\x18\x02 \x01(\tR\x07premise\x12\x14\n\x05\x63laim\x18\x03 \x01(\tR\x05\x63laim\"Y\n\x12\x45ntailmentsRequest\x12\x43\n\x07queries\x18\x01 \x03(\x0b\x32).arg_services.mining.v1.EntailmentRequestR\x07queries\"\x92\x01\n\x12\x45ntailmentResponse\x12\x42\n\nprediction\x18\x01 \x01(\x0e\x32\".arg_services.mining.v1.PredictionR\nprediction\x12\x38\n\x07\x64\x65tails\x18\x02 \x03(\x0b\x32\x1e.arg_services.mining.v1.DetailR\x07\x64\x65tails\"[\n\x13\x45ntailmentsResponse\x12\x44\n\x07results\x18\x01 \x03(\x0b\x32*.arg_services.mining.v1.EntailmentResponseR\x07results\"n\n\x06\x44\x65tail\x12 \n\x0bprobability\x18\x01 \x01(\x01R\x0bprobability\x12\x42\n\nprediction\x18\x02 \x01(\x0e\x32\".arg_services.mining.v1.PredictionR\nprediction*y\n\nPrediction\x12\x1a\n\x16PREDICTION_UNSPECIFIED\x10\x00\x12\x19\n\x15PREDICTION_ENTAILMENT\x10\x01\x12\x1c\n\x18PREDICTION_CONTRADICTION\x10\x02\x12\x16\n\x12PREDICTION_NEUTRAL\x10\x03\x32\xe0\x01\n\x11\x45ntailmentService\x12\x63\n\nEntailment\x12).arg_services.mining.v1.EntailmentRequest\x1a*.arg_services.mining.v1.EntailmentResponse\x12\x66\n\x0b\x45ntailments\x12*.arg_services.mining.v1.EntailmentsRequest\x1a+.arg_services.mining.v1.EntailmentsResponseB\xb2\x01\n)de.uni_trier.recap.arg_services.mining.v1B\x0f\x45ntailmentProtoP\x01\xa2\x02\x03\x41MX\xaa\x02\x15\x41rgServices.Mining.V1\xca\x02\x15\x41rgServices\\Mining\\V1\xe2\x02!ArgServices\\Mining\\V1\\GPBMetadata\xea\x02\x17\x41rgServices::Mining::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arg_services.mining.v1.entailment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)de.uni_trier.recap.arg_services.mining.v1B\017EntailmentProtoP\001\242\002\003AMX\252\002\025ArgServices.Mining.V1\312\002\025ArgServices\\Mining\\V1\342\002!ArgServices\\Mining\\V1\\GPBMetadata\352\002\027ArgServices::Mining::V1'
  _PREDICTION._serialized_start=609
  _PREDICTION._serialized_end=730
  _ENTAILMENTREQUEST._serialized_start=67
  _ENTAILMENTREQUEST._serialized_end=162
  _ENTAILMENTSREQUEST._serialized_start=164
  _ENTAILMENTSREQUEST._serialized_end=253
  _ENTAILMENTRESPONSE._serialized_start=256
  _ENTAILMENTRESPONSE._serialized_end=402
  _ENTAILMENTSRESPONSE._serialized_start=404
  _ENTAILMENTSRESPONSE._serialized_end=495
  _DETAIL._serialized_start=497
  _DETAIL._serialized_end=607
  _ENTAILMENTSERVICE._serialized_start=733
  _ENTAILMENTSERVICE._serialized_end=957
# @@protoc_insertion_point(module_scope)
