# Part of the ROBOID project - http://hamster.school
# Copyright (C) 2016 Kwang-Hyun Park (akaii@kw.ac.kr)
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA  02111-1307  USA 

import base64, codecs
magic = 'IyBQYXJ0IG9mIHRoZSBST0JPSUQgcHJvamVjdCAtIGh0dHA6Ly9oYW1zdGVyLnNjaG9vbA0KIyBDb3B5cmlnaHQgKEMpIDIwMTYgS3dhbmctSHl1biBQYXJrIChha2FpaUBrdy5hYy5rcikNCiMgDQojIFRoaXMgbGlicmFyeSBpcyBmcmVlIHNvZnR3YXJlOyB5b3UgY2FuIHJlZGlzdHJpYnV0ZSBpdCBhbmQvb3INCiMgbW9kaWZ5IGl0IHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGUgR05VIExlc3NlciBHZW5lcmFsIFB1YmxpYw0KIyBMaWNlbnNlIGFzIHB1Ymxpc2hlZCBieSB0aGUgRnJlZSBTb2Z0d2FyZSBGb3VuZGF0aW9uOyBlaXRoZXINCiMgdmVyc2lvbiAyLjEgb2YgdGhlIExpY2Vuc2UsIG9yIChhdCB5b3VyIG9wdGlvbikgYW55IGxhdGVyIHZlcnNpb24uDQojIA0KIyBUaGlzIGxpYnJhcnkgaXMgZGlzdHJpYnV0ZWQgaW4gdGhlIGhvcGUgdGhhdCBpdCB3aWxsIGJlIHVzZWZ1bCwNCiMgYnV0IFdJVEhPVVQgQU5ZIFdBUlJBTlRZOyB3aXRob3V0IGV2ZW4gdGhlIGltcGxpZWQgd2FycmFudHkgb2YNCiMgTUVSQ0hBTlRBQklMSVRZIG9yIEZJVE5FU1MgRk9SIEEgUEFSVE'
love = 'yQIHkOHvODIIWDG1ASYvNtH2IyVUEbMFOUGyHAPvZtGTImp2IlVRqyozIlLJjtHUIvoTywVRkcL2Ihp2HtMz9lVT1ipzHtMTI0LJyfpl4APvZtQDbwVSyiqFOmnT91oTDtnTS2MFOlMJAynKMyMPOuVTAipUxto2LtqTuyVRqBIFOZMKAmMKVtE2IhMKWuoN0XVlODqJWfnJZtGTywMJ5mMFOuoT9hMlO3nKEbVUEbnKZtoTyvpzSlrGftnJLtoz90YPO3pzy0MFO0olO0nTHAPvZtEaWyMFOGo2M0q2SlMFOTo3IhMTS0nJ9hYPOWozZhYPN1BFOHMJ1joTHtHTkuL2HfVSA1nKEyVQZmZPjAPvZtDz9mqT9hYPOADFNtZQVkZGRgZGZjAlNtIIAOQDbAPzygpT9lqPOgLKEbQDccoKOipaDto3ZAPt0XQDcwoTSmplOIqTyfBt0XVPNtVROmqTS0nJAgMKEbo2DAPvNtVPOxMJLtMTymqTShL2HbpUDkYPOjqQVcBt0XVPNtVPNtVPOcMvOjqQRtnKZtoz90VR5iozHtLJ5xVUO0ZvOcplOho3DtGz9hMGbAPvNtVPNtVPNtVPNtVTkyozq0nPN9VT1covufMJ4bpUDkXFjtoTIhXUO0ZvxcQDbtVPNtVPNtVPNtVPOmqJ0tCFNjQDbtVPNtVPNtVPNtVPOzo3VtnFOcovOlLJ5aMFufMJ5aqTtcBt0XVPNt'
god = 'ICAgICAgICAgICAgIHN1bSArPSAocHQxW2ldIC0gcHQyW2ldKSAqKiAyDQogICAgICAgICAgICByZXR1cm4gbWF0aC5zcXJ0KHN1bSkNCiAgICAgICAgcmV0dXJuIE5vbmUNCg0KICAgIEBzdGF0aWNtZXRob2QNCiAgICBkZWYgZGVncmVlKHB0MSwgcHQyKToNCiAgICAgICAgaWYgcHQxIGlzIG5vdCBOb25lIGFuZCBwdDIgaXMgbm90IE5vbmU6DQogICAgICAgICAgICB4ID0gcHQyWzBdIC0gcHQxWzBdDQogICAgICAgICAgICB5ID0gcHQxWzFdIC0gcHQyWzFdDQogICAgICAgICAgICByZXR1cm4gbWF0aC5kZWdyZWVzKG1hdGguYXRhbjIoeSwgeCkpDQogICAgICAgIHJldHVybiBOb25lDQoNCiAgICBAc3RhdGljbWV0aG9kDQogICAgZGVmIHJhZGlhbihwdDEsIHB0Mik6DQogICAgICAgIGlmIHB0MSBpcyBub3QgTm9uZSBhbmQgcHQyIGlzIG5vdCBOb25lOg0KICAgICAgICAgICAgeCA9IHB0MlswXSAtIHB0MVswXQ0KICAgICAgICAgICAgeSA9IHB0MVsxXSAtIHB0MlsxXQ0KICAgICAgICAgICAgcmV0dXJuIG1hdGguYXRhbjIoeSwgeCkNCiAgICAgICAgcmV0dXJuIE'
destiny = '5iozHAPt0XVPNtVROmqTS0nJAgMKEbo2DAPvNtVPOxMJLtpzIuoTy6MI9znJkypTS0nPuznJkypTS0nPx6QDbtVPNtVPNtVTyzVTymnJ5mqTShL2HbMzyfMKOuqTtfVUA0pvx6QDbtVPNtVPNtVPNtVPOzo2kxMKVtCFOipl5jLKEbYzEcpz5uoJHbMzyfMKOuqTtcQDbtVPNtVPNtVPNtVPOcMvOho3Dto3ZhpTS0nP5cp2Ecpvuzo2kxMKVcBt0XVPNtVPNtVPNtVPNtVPNtVT9mYz1un2IxnKWmXTMioTEypvxAPt0XQDcwoTSmplOTo250IKEcoQbAPvNtVPOsEx9BIPN9VR5iozHAPvNtVPNAPvNtVPONp3EuqTywoJI0nT9xQDbtVPNtMTIzVTqyqS9zo250XPx6QDbtVPNtVPNtVTyzVRMioaEIqTyfYy9TG05HVTymVR5iozH6QDbtVPNtVPNtVPNtVPOzpz9gVSOWGPOcoKOipaDtFJ1uM2ITo250QDbtVPNtVPNtVPNtVPOTo250IKEcoP5sEx9BIPN9VRygLJqyEz9hqP50paIyqUyjMFuipl5mMKNhnz9covuoo3ZhpTS0nP5xnKWhLJ1yXT9mYaOuqTthpzIuoUOuqTtbK19znJkyK18cXFjtW21uoTq1ov50qTLaKFxfVQRlXD0XVPNtVPNtVPOlMKE1pz4tEz9hqSI0nJjhK0MCGyDAPt=='
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))