[tool.poetry]
name = "tickcounter"
version = "0.2.3"
description = "A library for processing survey data"
authors = ["Ong Eng Kheng"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1"
pandas = ">=1.3.5"
scipy = ">=1.4.1"
matplotlib = ">=3.2.2"
seaborn = ">=0.11.2"
pyyaml = ">=6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
