[tool.black]
line-length = 127
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
    __pycache__
  | \.git
  | \.pytest_cache
  | \.vscode
  | docs
  | build
  | third_party
)/
'''
