[tool.poetry]
name = "mpbroker"
version = "0.2.0"
description = "Media Player Broker"
authors = ["David Rader <sa@adercon.com>"]
readme = "README.md"

[tool.poetry.scripts]
mpb = "mpbroker.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.4.1"}
arrow = "^1.2.2"
pycouchdb = "^1.14.1"
pydantic = "^1.9.0"
requests = "^2.27.1"
rich = "^12.3.0"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
