[internal]
created = 2015-09-15

[tool.poetry]
name = "spw"
version = "1.7.0"
description = "store and retrieve passwords securely all while being scriptable!"
authors = ["David Rader <sa@adercon.com>"]
maintainers = ["David Rader <sa@adercon.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://gitlab.com/drad/spw"
repository = "https://gitlab.com/drad/spw"
keywords = ["cli", "encryption", "password", "openbox", "scriptable"]

[tool.poetry.scripts]
spw = "spw.main:app"

[tool.poetry.dependencies]
python = "^3.7"
lmdb = "^1.3.0"
pyperclip = "^1.8.2"
cryptography = "^36.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | app/migrations
)/
'''
