version: '3.7'

services:

  car.neo4j:
    container_name: car.neo4j
    image: ghcr.io/qtc-de/container-arsenal/neo4j:1.0.0
    build: .
    environment:
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_neo4j_folder}:/data
      - ./scripts/start.sh:/scripts/start.sh
    ports:
      - "${car_http_port}:7474"
      - "${car_bolt_port}:7687"
