version: '3.7'

services:

  car.h2b:
    container_name: car.h2b
    image: ghcr.io/qtc-de/container-arsenal/h2b:1.0.0
    build: .
    environment:
      FLASK_PORT: ${car_http_port}
    volumes:
      - ./scripts/start.sh:/scripts/start.sh
      - ./scripts/h2b.py:/scripts/h2b.py
    network_mode: "host"
