[build-system]
# https://setuptools.pypa.io/en/latest/build_meta.html
requires = [
         "setuptools >= 40.4",
         "wheel",
         ]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories in the root of the project
^/setup.py
# exclude the parameter checking code, which has some intentionally tight lines
^/sirius/\_parm\_utils\/*
'''
