[tool.poetry]
name = "text-gists"
version = "0.0.1"
description = "Helper functions for matching regex and other text-based patterns."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.2"

[tool.poetry.group.dev.dependencies]
types-python-dateutil = "^2.8.14"
pytest = "^7.1"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
mypy = "^0.942"
black = "^22.3.0"
isort = "^5.10"
pre-commit = "^2.18"
ipykernel = "^6.12"
tqdm = "^4.64"


[tool.pytest]
minversion = "6.0"
addopts = "-ra -q --cov=regex_gists tests/"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''


[build-system]
requires = ["poetry-core>=1.1.12"]
build-backend = "poetry.core.masonry.api"
