[project]
name = "pdm-mina"
version = "0.1.0"
description = "multi-publish for a series of packages which from a python package"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = [
    "pdm>=1.14.1",
    "mina-build>=0.1.7",
]
requires-python = ">=3.9"
readme = "README.md"
mina-package = "cli-pdm"
includes = [
    "mina",
]
excludes = [
    "mina/backend",
]

[project.license]
text = "MIT"

[project.optional-dependencies]

[project.entry-points.pdm]
mina = "mina.plugin:ensure_pdm"

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "isort>=5.10.1",
    "devtools>=0.8.0",
]

[tool.mina]
enabled = true

[tool.mina.packages.backend]
name = "mina-build"
version = "0.1.7"
description = "build backend for Mina Package Structure"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = [
    "pdm-pep517",
]
requires-python = ">=3.9"
readme = "README.build.md"
includes = [
    "mina/backend",
]

[tool.mina.packages.backend.license]
text = "MIT"

[tool.mina.packages.backend.entry-points]

[tool.mina.packages.cli-pdm]
name = "pdm-mina"
version = "0.1.0"
includes = [
    "mina",
]
excludes = [
    "mina/backend",
]
dependencies = [
    "pdm",
    "mina-build",
]
requires-python = ">=3.9"
readme = "README.md"

[tool.mina.packages.cli-pdm.license]
text = "MIT"

[tool.mina.packages.cli-pdm.entry-points.pdm]
mina = "mina.plugin:ensure_pdm"

[build-system]
requires = [
    "mina-build>=0.1.7",
]
build-backend = "mina.backend"
