
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T17:09:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03b72dc955fb2d048912999d658283ac37b98bee",
 "version": "1.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
