version: '3.7'

services:

  car.samba:
    container_name: car.samba
    image: ghcr.io/qtc-de/container-arsenal/samba:1.0.1
    build: .
    environment:
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_public_folder}:/share/public
      - ${car_private_folder}:/share/private
      - ./scripts/start.sh:/scripts/start.sh
      - ./config/smb.conf:/config/smb.conf
    ports:
      - "${car_smb_port}:445"
