[tool.poetry]
name = "amplified"
version = "0.0.0"
description = "Amplify your Python developer experience"
authors = ["Jeroen Schot <jeroenschot@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
