[tool.poetry]
name = "phobos"
version = "v1.2.9"
description = "Training utility library and config manager for Granular Machine Vision research"
authors = ["Sagar Verma <sagar@granular.ai>", "Siddharth Gupta <sid@granular.ai>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]
repository='https://github.com/granularai/phobos'

[tool.poetry.scripts]
phobos = 'phobos.cli:cli'

[tool.poetry.dependencies]
python = "^3.7.0"
torch = "^1.10.1"
polyaxon = "^1.10.1"
polyaxon-sdk = "^1.10.1"
numpy = "^1.21.0"
pytorch-lightning = "^1.3.8"
scikit-learn = "^0.24.2"
albumentations = "^1.0.3"
webdataset = "0.1.62"
cookiecutter = "^1.7.3"
torchvision = "^0.11.2"
timm = "0.5.4"
yacs = "^0.1.8"
boto3 = "^1.21.36"
rasterio = "^1.2.10"
Shapely = "^1.8.1"
pretrainedmodels = "^0.7.4"
efficientnet-pytorch = "^0.7.1"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
pip = "^21.1.3"
beautifulsoup4 = "^4.10.0"
bump2version = "^1.0.1"
watchdog = "^2.1.3"
flake8 = "^3.9.2"
tox = "^3.24.0"
coverage = "^5.5"
Sphinx = "^4.1.1"
twine = "^3.4.1"
pytest = "^6.2.4"
sphinx-rtd-theme = "^0.5.2"
sphinx-issues = "^1.2.0"
sphinx-prompt = "^1.4.0"
numpydoc = "^1.1.0"

[tool.poe.tasks]
torch-cuda11 = "python -m pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

