[tool.poetry]
name = "merakitools"
version = "0.1.9.1"
description = "CLI tools for managing Meraki networks based on Typer"
authors = ["Billy Zoellers <billy.zoellers@mac.com>"]
readme = "README.md"

[tool.poetry.scripts]
merakitools = "merakitools.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.3.2"}
rich = "^10.16.2"
meraki = "^1.20.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
typer-cli = "^0.0.12"
black = "^21.9b0"
pylint = "^2.13.7"
bandit = {extras = ["toml"], version = "^1.7.4"}

[tool.poetry.urls]
documentation = "https://github.com/billyzoellers/merakitools/README.md"
source = "https://github.com/billyzoellers/merakitools"
tracker = "https://github.com/billyzoellers/merakitools/issues"

[tool.black]
preview = true

[tool.bandit]
skips = ["B101",]

[tool.pylint.format]
max-line-legth = "88"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
