[tool.poetry]
name = "let_me_google_that_for_you"
version = "0.0.2"
description = "Package"
authors = ["Your Name <you@example.com>"]
license = "Package"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
