
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-28T09:26:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "db29417a6fdb22f5fb8a9f82caf1c000f6153423",
 "version": "0.15.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
