
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T12:30:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "98198e31e43280264bacd0fa4eb0f9babccd3fb8",
 "version": "v1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
