version: '3.7'

services:

  car.nginx:
    container_name: car.nginx
    image: ghcr.io/qtc-de/container-arsenal/nginx:1.1.0
    build: .
    environment:
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_upload_folder}:/var/www/html/upload/
      - ${car_download_folder}:/var/www/html/download/
      - ./config:/etc/nginx/http.d
      - ./scripts/start.sh:/scripts/start.sh
    ports:
      - "${car_http_port}:80"
      - "${car_https_port}:443"
