
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-27T18:38:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "59fae4aec63022dc13f158ff88490bdad8da551c",
 "version": "v0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
