[build-system]
requires = [
    "setuptools>=51.0.0",
    "wheel"
]


[tool.black]
target-version = ['py38', 'py39']
exclude = '''
(
    \.egg
    | \.hg
    | \.git
    | \.github
    | \.nox
    | \.tox
    | \.venv
    | build
    | dist
    | setup.py
    | build.py
    | \.env

)
'''
