# This workflow will build on multiple versions or python and OS.

name: pip-installs

# Run on push to main, PR's and manually
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pypi_deploy:

    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-20.04"]
        python-version: ["3.8", "3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install with pip
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .
      - name: Test the import
        run: python -c "import parallel_docker_build;"
      - name: Test the CLI help
        run: parallel-docker-build -h
