[tool.poetry]
name = "diffql"
version = "0.2.1"
description = "Differentiable Q-learning (DiffQL) for continuous-action deep reinforcement learning"
authors = ["Jinrae Kim <kjl950403@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
torch = ">=1.11,<1.12"
scipy = ">=1.8,<1.9"
numpy = ">=1.22,<1.23"
cvxpy = ">=1.2,<1.3"
cvxpylayers = ">=0.1,<0.2"
gym = ">=0.22,<0.23"
Mosek = ">=9.3,<9.4"
PyYAML = ">=6.0,<6.1"
wandb = ">=0.12,<0.13"

[tool.poetry.dev-dependencies]
ipython = "^8.0.1"
matplotlib = "^3.5.1"
pytest = "^6.2.5"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
