
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-29T18:28:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b92c3cf60114f9df34a0091c2f3651a2f08e243",
 "version": "0.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
