[tool.poetry]
name = "kedroio"
version = "0.1.3"
description = "Extension for `kedro` datasets"
authors = ["atsangarides <andreas_tsangarides@hotmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/atsangarides/kedroio"
repository = "https://github.com/atsangarides/kedroio"
keywords = ["data pipelines", "kedro"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.20.17"
tqdm = "^4.62.3"
boto3-stubs = {extras = ["s3"], version = "^1.20.24"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-env = "^0.6.2"
moto = {extras = ["server"], version = "^2.3.0"}
requests = "^2.26.0"
kedro = {version = "0.17.6", python = ">=3.8,<3.9"}
PyYAML = "5.4.1"
pandas = "^1.3.4"
SQLAlchemy = "^1.4.27"
PyHive = {extras = ["hive"], version = "^0.6.4"}
black = "^21.12b0"
pre-commit = "^2.16.0"

[tool.black]
line-length = 89
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.python-version
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
