[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
strip = true

[project]
name = "evg-task-profiler-py"
requires-python = ">=3.7"
readme = "README.md"
authors = [
    {name = "David Bradford", email = "david.bradford@mongodb.com"}
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
homepage = "https://github.com/dbradf/evg-task-profiler.py"
repository = "https://github.com/dbradf/evg-task-profiler.py"
