[tool.poetry]
name = "YetAnotherPicSearch"
version = "1.4.0"
description = "Yet Another Picture Search Nonebot Plugin"
authors = ["NekoAria"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "YetAnotherPicSearch" },
]
homepage = "https://github.com/NekoAria/YetAnotherPicSearch"
repository = "https://github.com/NekoAria/YetAnotherPicSearch"
keywords = ["nonebot", "saucenao", "ascii2d", "pixiv", "danbooru", "anime"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.8.1"
arrow = "^1.2.0"
nonebot-adapter-onebot = "^2.0.0b1"
nonebot2 = "^2.0.0b1"
PicImageSearch = "^3.1.9"
pydantic = "^1.9.0"
pyquery = "^1.4.3"
tinydb = "^4.6.1"
yarl = "^1.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
