[tool.poetry]
name = "security-headers-scan"
version = "0.1.0"
description = ""
authors = ["Pat <patrick.turner@nhs.net>"]
packages = [
    { include = "security_headers" }
]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.3"
python-dotenv = "^0.19.2"
semantic-version = "^2.9.0"
requests = "^2.27.1"
certifi = "^2021.10.8"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
httpretty = "^1.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
