LX_POS_TAGS = {
    "ADJ",
    "ADV",
    "CARD",
    "CJ",
    "CL",
    "CN",
    "DA",
    "DEM",
    "DFR",
    "DGT",
    "DGTR",
    "DM",
    "EADR",
    "EL",
    "EMP",
    "EOE",
    "EXC",
    "GER",
    "IA",
    "IND",
    "INF",
    "INT",
    "ITJ",
    "LADV1",
    "LADV2",
    "LADV3",
    "LADV4",
    "LADV5",
    "LADV6",
    "LADV7",
    "LCJ1",
    "LCJ2",
    "LCJ3",
    "LCJ4",
    "LCJ5",
    "LD1",
    "LD2",
    "LDEM1",
    "LDEM2",
    "LDFR1",
    "LDFR2",
    "LDM1",
    "LDM2",
    "LDM3",
    "LINT1",
    "LINT2",
    "LITJ1",
    "LITJ2",
    "LITJ3",
    "LPREP1",
    "LPREP2",
    "LPREP3",
    "LPREP4",
    "LPREP5",
    "LPREP6",
    "LPRS1",
    "LPRS2",
    "LQD1",
    "LQD2",
    "LREL1",
    "LREL2",
    "LTR",
    "MGT",
    "MTH",
    "NP",
    "NULL",
    "ORD",
    "PADR",
    "PL",
    "PNM",
    "PNT",
    "POSS",
    "PP",
    "PPA",
    "PPT",
    "PREP",
    "PRS",
    "QNT",
    "REL",
    "SC",
    "STT",
    "SYB",
    "TERMN",
    "UM",
    "UNIT",
    "V",
    "VAUX",
    "VAUXGER",
    "VAUXINF",
    "WD",
}

U_POS_TAGS = {
    "ADJ",
    "ADP",
    "ADV",
    "AUX",
    "CCONJ",
    "DET",
    "INT",
    "INTJ",
    "NOUN",
    "NUM",
    "PRON",
    "PROPN",
    "PUNCT",
    "SCONJ",
    "SYM",
    "VERB",
    "X",
}

LX_DEPREL_TAGS = {
    "ADV",
    "C-ARG1",
    "C-ARG2",
    "C-ARG3",
    "C",
    "CARD",
    "CONJ",
    "COORD",
    "DEM",
    "DEP",
    "DM",
    "DO-ARG1",
    "DO-ARG2",
    "DO-ARG21",
    "DO-ARG3",
    "DO-TMP",
    "DO",
    "ERROR",
    "INT",
    "IO-ARG2",
    "IO-ARG3",
    "IO-ARG31",
    "ITJ",
    "M-ADV",
    "M-ARG1",
    "M-ARG2",
    "M-CAU",
    "M-DIR",
    "M-EXT",
    "M-LOC",
    "M-M",
    "M-MNR",
    "M-PNC",
    "M-POV",
    "M-PRED",
    "M-TMP",
    "M",
    "N",
    "OBL-ADV",
    "OBL-ARG1",
    "OBL-ARG2",
    "OBL-ARG3",
    "OBL-ARG4",
    "ORD",
    "P",
    "PERCENT",
    "POSS",
    "PRD-ARG2",
    "PRD-ARG3",
    "PRD-ARG4",
    "PRD",
    "PRS",
    "PUNCT",
    "QNT",
    "REL",
    "ROOT",
    "S",
    "SJ-ARG1",
    "SJ-ARG11",
    "SJ-ARG11cp",
    "SJ-ARG1cp",
    "SJ-ARG2",
    "SJ-ARG21cp",
    "SJ-ARG2ac",
    "SJ-ARG2cp",
    "SJ",
    "SP-ARG1",
    "SP-ARG2",
    "SP-M",
    "SP-PRED",
    "SP",
    "V",
}

U_DEPREL_TAGS = {
    # only contains UD V2 tags that occur in CINTIL, i.e. tags known to our DepParser
    "advcl",
    "advmod",
    "amod",
    "appos",
    "aux",
    "case",
    "cc",
    "ccomp",
    "comp",
    "conj",
    "cop",
    "csubj:pass",
    "csubj",
    "dep",
    "det",
    "fixed",
    "iobj",
    "mark",
    "mod",
    "nsubj",
    "num",
    "number",
    "obj",
    "parataxis",
    "pobj",
    "poss",
    "preconj",
    "predet",
    "punct",
    "root",
    "xcomp",
}

U_DEPREL_TAGS_V1_TO_V2 = {
    # https://universaldependencies.org/v2/summary.html#clauses-and-dependents-of-predicates
    "dobj": "obj",
    "nsubjpass": "nsubj:pass",  # does not occur in CINTIL
    "csubjpass": "csubj:pass",
    "auxpass": "aux:pass",  # does not occur in CINTIL
    # https://universaldependencies.org/v2/summary.html#multiword-expressions
    "mwe": "fixed",
}

LX_FEATS = {
    "1p",
    "1s",
    "2p",
    "2s",
    "3p",
    "3s",
    "c-1p",
    "c-1s",
    "c-2p",
    "c-2s",
    "c-3p",
    "c-3s",
    "fc-1p",
    "fc-1s",
    "fc-2s",
    "fc-3p",
    "fc-3s",
    "fi-1p",
    "fi-1s",
    "fi-2p",
    "fi-2s",
    "fi-3p",
    "fi-3s",
    "fp-comp",
    "fp-dim",
    "fp-sup",
    "fp",
    "fp1",
    "fp2",
    "fp3",
    "fs-comp-dim",
    "fs-comp",
    "fs-dim",
    "fs-sup",
    "fs",
    "fs1",
    "fs2",
    "fs3",
    "gn",
    "gn13",
    "gn3",
    "gp-comp",
    "gp",
    "gp1",
    "gp2",
    "gp3",
    "gs-comp",
    "gs-sup",
    "gs",
    "gs1",
    "gs2",
    "gs3",
    "ic-1p",
    "ic-1s",
    "ic-2s",
    "ic-3p",
    "ic-3s",
    "ii-1p",
    "ii-1s",
    "ii-2s",
    "ii-3p",
    "ii-3s",
    "imp-1p",
    "imp-2p",
    "imp-2s",
    "imp-Cp",
    "imp-Cs",
    "impaf-2p",
    "impaf-2s",
    "impneg-2p",
    "impneg-2s",
    "mn",
    "mp-comp",
    "mp-dim",
    "mp-sup",
    "mp",
    "mp1",
    "mp2",
    "mp3",
    "mpC",
    "mpi-1p",
    "mpi-1s",
    "mpi-3p",
    "mpi-3s",
    "ms-comp-dim",
    "ms-comp",
    "ms-dim",
    "ms-sup-dim",
    "ms-sup",
    "ms",
    "ms1",
    "ms2",
    "ms3",
    "ndef",
    "ninf",
    "np",
    "pc-1p",
    "pc-1s",
    "pc-2p",
    "pc-2s",
    "pc-3p",
    "pc-3s",
    "pi-1p",
    "pi-1s",
    "pi-2p",
    "pi-2s",
    "pi-3p",
    "pi-3s",
    "pi-Cp",
    "ppi-1p",
    "ppi-1s",
    "ppi-2p",
    "ppi-2s",
    "ppi-3p",
    "ppi-3s",
}

LX_FEATS_TO_U_FEATS = {
    "1p": "Person=1|Number=Plur",
    "1s": "Person=1|Number=Sing",
    "2p": "Person=2|Number=Plur",
    "2s": "Person=2|Number=Sing",
    "3p": "Person=3|Number=Plur",
    "3s": "Person=3|Number=Sing",
    "c-1p": "c-1p",
    "c-1s": "c-1s",
    "c-2p": "c-2p",
    "c-2s": "c-2s",
    "c-3p": "c-3p",
    "c-3s": "c-3s",
    "fc-1p": "fc-1p",
    "fc-1s": "fc-1s",
    "fc-2s": "fc-2s",
    "fc-3p": "fc-3p",
    "fc-3s": "fc-3s",
    "fi-1p": "fi-1p",
    "fi-1s": "fi-1s",
    "fi-2p": "fi-2p",
    "fi-2s": "fi-2s",
    "fi-3p": "fi-3p",
    "fi-3s": "fi-3s",
    "fp-comp": "fp-comp",
    "fp-dim": "fp-dim",
    "fp-sup": "fp-sup",
    "fp": "Gender=Fem|Number=Plur",
    "fp1": "Gender=Fem|Number=Plur|Person=1",
    "fp2": "Gender=Fem|Number=Plur|Person=2",
    "fp3": "Gender=Fem|Number=Plur|Person=3",
    "fs-comp-dim": "fs-comp-dim",
    "fs-comp": "fs-comp",
    "fs-dim": "fs-dim",
    "fs-sup": "fs-sup",
    "fs": "Gender=Fem|Number=Sing",
    "fs1": "Gender=Fem|Number=Sing|Person=1",
    "fs2": "Gender=Fem|Number=Sing|Person=2",
    "fs3": "Gender=Fem|Number=Sing|Person=3",
    "gn": "Gender=Com|Number=Ptan",  # dúvidas g => Com? n => Ptan?
    "gn1": "Gender=Com|Number=Ptan|Person=1",  # dúvidas g => Com? n => Ptan?
    "gn2": "Gender=Com|Number=Ptan|Person=2",  # dúvidas g => Com? n => Ptan? (gn2 não ocorre no CINTIL)  # noqa: E501
    "gn3": "Gender=Com|Number=Ptan|Person=3",  # dúvidas g => Com? n => Ptan?
    "gn13": "Gender=Com|Number=Ptan|Person=1|Person=3",  # dúvidas g => Com? n => Ptan?, como traduzir 13?  # noqa: E501
    "gp-comp": "gp-comp",
    "gp": "Gender=Com|Number=Plur",
    "gp1": "Gender=Com|Number=Plur|Person=1",  # dúvidas g => Com
    "gp2": "Gender=Com|Number=Plur|Person=2",  # dúvidas g => Com
    "gp3": "Gender=Com|Number=Plur|Person=3",  # dúvidas g => Com
    "gs-comp": "gs-comp",
    "gs-sup": "gs-sup",
    "gs": "Gender=Com|Number=Sing",
    "gs1": "Gender=Com|Number=Sing|Person=1",  # dúvidas g => Com
    "gs2": "Gender=Com|Number=Sing|Person=2",  # dúvidas g => Com
    "gs3": "Gender=Com|Number=Sing|Person=3",  # dúvidas g => Com
    "ic-1p": "ic-1p",
    "ic-1s": "ic-1s",
    "ic-2s": "ic-2s",
    "ic-3p": "ic-3p",
    "ic-3s": "ic-3s",
    "ii-1p": "ii-1p",
    "ii-1s": "ii-1s",
    "ii-2s": "ii-2s",
    "ii-3p": "ii-3p",
    "ii-3s": "ii-3s",
    "imp-1p": "imp-1p",
    "imp-2p": "imp-2p",
    "imp-2s": "imp-2s",
    "imp-Cp": "imp-Cp",
    "imp-Cs": "imp-Cs",
    "impaf-2p": "impaf-2p",
    "impaf-2s": "impaf-2s",
    "impneg-2p": "impneg-2p",
    "impneg-2s": "impneg-2s",
    "mn": "mn",
    "mp-comp": "mp-comp",
    "mp-dim": "mp-dim",
    "mp-sup": "mp-sup",
    "mp": "mp",
    "mp1": "mp1",
    "mp2": "mp2",
    "mp3": "mp3",
    "mpC": "mpC",
    "mpi-1p": "mpi-1p",
    "mpi-1s": "mpi-1s",
    "mpi-3p": "mpi-3p",
    "mpi-3s": "mpi-3s",
    "ms-comp-dim": "ms-comp-dim",
    "ms-comp": "ms-comp",
    "ms-dim": "ms-dim",
    "ms-sup-dim": "ms-sup-dim",
    "ms-sup": "ms-sup",
    "ms": "ms",
    "ms1": "ms1",
    "ms2": "ms2",
    "ms3": "ms3",
    "ndef": "ndef",
    "ninf": "ninf",
    "np": "np",
    "pc-1p": "pc-1p",
    "pc-1s": "pc-1s",
    "pc-2p": "pc-2p",
    "pc-2s": "pc-2s",
    "pc-3p": "pc-3p",
    "pc-3s": "pc-3s",
    "pi-1p": "pi-1p",
    "pi-1s": "pi-1s",
    "pi-2p": "pi-2p",
    "pi-2s": "pi-2s",
    "pi-3p": "pi-3p",
    "pi-3s": "pi-3s",
    "pi-Cp": "pi-Cp",
    "ppi-1p": "ppi-1p",
    "ppi-1s": "ppi-1s",
    "ppi-2p": "ppi-2p",
    "ppi-2s": "ppi-2s",
    "ppi-3p": "ppi-3p",
    "ppi-3s": "ppi-3s",
}

U_FEATS = set(LX_FEATS_TO_U_FEATS.values())

NE_TAGS = {
    "B-EVT",
    "B-LOC",
    "B-MSC",
    "B-ORG",
    "B-PER",
    "B-WRK",
    "I-EVT",
    "I-LOC",
    "I-MSC",
    "I-ORG",
    "I-PER",
    "I-WRK",
    "O",
}

LX_POS_TO_U_POS = {
    "ADJ": "ADJ",
    "ADV": "ADV",
    "CARD": "NUM",
    "CJ": (lambda form: "CCONJ" if form.lower() in ["e", "mas", "ou"] else "SCONJ"),
    "CL": "PRON",
    "CN": "NOUN",
    "DA": "DET",
    "DEM": "DET",
    "DFR": "NUM",
    "DGT": "NUM",
    "DGTR": "NUM",
    "DM": "INTJ",
    "EADR": "SYM",
    "EL": "INTJ",  # extralinguistic (CINTIL Corpus)
    "EMP": "ADV",
    "EOE": "NOUN",
    "EXC": "INT",  # exclamative (CINTIL Corpus)
    "GER": "VERB",
    "IA": "DET",
    "IND": "PRON",
    "INF": "VERB",
    "INT": "PRON",
    "ITJ": "INTJ",
    "LTR": "SYM",
    "MGT": "NOUN",
    "MTH": "NOUN",
    "NP": "X",  # "noun phrase" word (CINTIL Corpus)
    "ORD": "ADJ",
    "PADR": "NOUN",
    "PL": "INTJ",  # paralinguistic (CINTIL Corpus)
    "PNM": "PROPN",
    "PNT": "PUNCT",
    "POSS": "PRON",
    "PP": (
        # "prepositional phrase" word (CINTIL Corpus)
        lambda form: "INT"
        if form.lower() in ["porquê"]
        else "X"
    ),
    "PPA": "VERB",
    "PPT": "VERB",
    "PREP": "ADP",
    "PRS": "PRON",
    "QNT": "DET",
    "REL": "PRON",
    "SC": "X",  # foreign? error? (CINTIL Corpus)
    "STT": "NOUN",
    "SYB": "SYM",
    "TERMN": "SYM",
    "UM": "DET",  # DET or NUM ?
    "UNIT": "NOUN",
    "V": "VERB",
    "VAUX": "AUX",
    "VAUXGER": "AUX",
    "VAUXINF": "AUX",
    "WD": "NOUN",
    "X": "X",  # error? (CINTIL Corpus)
    "_": "X",  # formating marks: <i>, <t>, etc. (CINTIL Corpus)
}
