[tool.poetry]
name = "externalpyoverlay"
version = "1.0.1"
description = "External python overlay to draw simple graphic primitives upon the window"
authors = ["Xenely <a.maryatkin14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
