[tool.poetry]
name = "ccc-cli"
version = "0.1.3"
description = "Command line utility for Carbon Copy Cloner"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/ccc-cli"
repository = "https://github.com/tddschn/ccc-cli"
keywords = ["git", "asyncio"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/ccc-cli/issues"

[tool.poetry.scripts]
cccls = "ccc_cli.ccc6_print_task_runs:main"

[tool.poetry.dependencies]
python = "^3.10"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10.2"
yapf = "^0.32.0"
better-exceptions = "^0.3.3"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
