# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/

[build-system]
requires = ["poetry_core>=1.0.0", "setuptools>=54.0.2", "tox", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "qary"
version = "0.7.5"
description = "A chatbot that assists rather than manipulates."
readme = "README.md"
authors = [
  "ProAI <hobs@proai.org>"
]
license = "MIT"
repository = "https://gitlab.com/tangibleai/qary"
homepage = "https://gitlab.com/tangibleai/qary"

# Keywords description https://python-poetry.org/docs/pyproject/#keywords
keywords = []  # Update me

# Pypi classifiers: https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.scripts]
# Entry points for the package https://python-poetry.org/docs/pyproject/#scripts
"qary" = "qary.clibot:main"

[tool.poetry.dependencies]
python = "^3.8.3,<3.10.0"
poetry = "^1.1.13"
pre-commit = "^2.18.1"
beautifulsoup4 = "^4.9.3,<5.0.0"
boto3 = "1.13.19"
botocore = "1.16.19"
ConfigArgParse = "1.2.2"
django = "^4.0.0"
docutils = "0.15.2"
edit-distance = "1.0.4"
elasticsearch = "^7.6.0,<8.0.0"
environment = "1.0.0"
gitpython = "3.1.1"
graphviz = "0.16"
html5lib = "1.1"
importlib_metadata = {version = "^1.6.0", python = "<3.8"}
jedi = "^0.18.0"
jupyter = "1.0.0"
lxml = "4.6.3"
# [required by Sphinx & m2r](https://github.com/CrossNox/m2r2/issues/40)
m2r = "0.2.1"
# [required by Sphinx & m2r](https://github.com/CrossNox/m2r2/issues/40)
mistune = "0.8.4"
nltk = "3.5"
pandas = "1.1.3"
# pre_commit = "2.3.0"
pronouncing = "0.2.0"
psutil = "5.8.0"
pytest-cov = "2.11.1"
pytest = "6.2.2"
python-dotenv = "^0.13.0,<0.14.0"
python-slugify = "4.0.0"
rapidfuzz = "0.9.1"
recommonmark = "0.6.0"
regex = "2020.4.4"
rich = "^9.8.2"
scikit-image = "^0.17.2,<0.18.0"
scikit-learn = "0.24.2"
scipy = "1.7.1"
seaborn = "0.10.0"
sentence_transformers = "2.0.0"
spacy = "^3.1.0,<4.0.0"
# en-core-web-md = "^3.1.0"
Sphinx = "3.0.3"
torch = "1.8.1"
tox = "^3.23.0"
tqdm = "^4.38.0,<4.39.0"
typer = {extras = ["all"], version = "^0.3.2"}
transformers = "4.10.0"
wikipedia-api = "0.5.4"
yake = "0.4.6"
pyyaml = "5.4.1"

[tool.poetry.dev-dependencies]
darglint = "^1.5.8"
isort = "^5.7.0"
pyupgrade = "^2.7.4"
black = "^20.8b1"
mypy = "^0.790"
bandit = "^1.7.0"
safety = "^1.10.3"
pytest = "^6.2.1"
pylint = "^2.6.0"
pydocstyle = "^5.1.1"
pre-commit = "^2.9.3"

[tool.black]
# https://github.com/psf/black
line-length = 80
target-version = ["py37"]

[tool.isort]
# https://github.com/timothycrosley/isort/
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
default_section = "FIRSTPARTY"
multi_line_output = 3
indent = 4
force_grid_wrap = 0
use_parentheses = true
line_length = 80
