[project]
name = "Rh-s-PyTool"
version = "0.0.1"
description = "Instruments used in school-project"
authors = [
    { name = "skahanium", email = "skahanium@gmail.com" },
]
readme = "README.md"
dependencies = [
    "numpy>=1.22.3",
]
requires-python = ">=3.10"

[project.license]
text = "MIT"

[tool.pdm]

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
