[tool.poetry]
name = "wlang-cli"
version = "0.1.4"
description = "A cli for the W programming language"
authors = ["James Butcher <jamesbutcher@duck.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"
wcore-py = "^0.5.1"
click = "^8.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
