[tool.poetry]
name = "ga4"
version = "0.1.0"
description = ""
authors = ["s4mukka <meninosam197@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
google-analytics-data = "^0.11.2"
pandas = "^1.4.2"
pyspark = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
