
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T04:06:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "60b94989dff571c4dfd67183953d3c2559e224ec",
 "version": "1.16.0.post.dev406"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
