[tool.poetry]
name = "itslive"
version = "0.1.1"
description = "Python client for ITSLIVE gralcier velocity data"
authors = ["betolink <luis.lopez@nsidc.org>"]
license = "GNUL V3"

[tool.poetry.dependencies]
python = "^3.9"
zarr = "^2.11.3"
s3fs = "^2022.3.0"
xarray = "^2022.3.0"
Shapely = "^1.8.1"
pyproj = "^3.3.1"
matplotlib = "^3.5.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"
pytest-watch = "^4.2.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
autoflake8 = "^0.3.2"
mkdocs = "^1.3.0"
mkdocs-material = ">=7.1,<9.0"
mkdocstrings = "^0.18.1"
pymdown-extensions = "^9.2"
jupyterlab = "^3.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
