[tool.poetry]
name = "formulaic"
version = "0.3.4"
description = "An implementation of Wilkinson formulas."
authors = ["Matthew Wardrop <mpwardrop@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/matthewwardrop/formulaic"
documentation = "https://matthewwardrop.github.io/formulaic"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
]

include = [
    { path = "docsite", format = "sdist" },
    { path = "benchmarks", format = "sdist" },
    { path = "tests", format = "sdist" },
    { path = "poetry.lock", format = "sdist" },
    { path = "tox.ini", format = "sdist" },
]

[tool.poetry-dynamic-versioning]
enable = false

[tool.poetry.build]
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.7.1"
astor = ">=0.8"
interface-meta = "^1.2.0"
numpy = ">=1.3"
pandas = ">=1.2"
scipy = ">=1.6"
wrapt = ">=1.0"
pyarrow = {version = ">=1", optional = true}
sympy = {version = ">=1.3,<1.10", optional = true}

[tool.poetry.extras]
arrow = ["pyarrow"]
calculus = ["sympy"]

[tool.poetry.dev-dependencies]
black = "^22.1"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
