[tool.poetry]
name = "CTN-ProtocolParser"
version = "0.1.1"
description = "Utility to parse protocols for the CTN islets framework."
license = "MIT"
authors = ["Johannes Pfabe <39130094+Hannnsen@users.noreply.github.com>"]
repository = "https://github.com/Hannnsen/protocol_parser"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Topic :: Utilities"
]
packages = [
    { include = "protocol_parser" }
]

[tool.poetry.scripts]
protocol_parser = "protocol_parser.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
