[tool.poetry]
name = "task-flows"
version = "0.1.1"
description = ""
authors = ["Dan <kelleherjdan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
alert-msgs = "^0.0.4"
SQLAlchemy = "^1.4.35"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"
python-dotenv = "^0.20.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
