[tool.poetry]
name = "deepgis-utils"
version = "0.1.2"
description = "A collection of utilities for DeepGIS"
authors = ["Xuanh.W <Xuanh.W.coding@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Rainlv/DeepGIS-utils"
repository = "https://github.com/Rainlv/DeepGIS-utils"

[tool.poetry.dependencies]
python = "^3.9"
geopandas = "~0.10.2"
SQLAlchemy = "~1.4.35"
psycopg2 = "~2.9.3"
GeoAlchemy2 = "~0.11.1"
requests = "~2.27.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
