[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.poetry]
name = "jedi-language-server"
version = "0.36.0"
description = "A language server for Jedi!"
authors = ["Sam Roeca <samuel.roeca@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/pappasam/jedi-language-server"
repository = "https://github.com/pappasam/jedi-language-server"
keywords = [
  "python",
  "completion",
  "refactoring",
  "vim",
  "neovim",
  "lsp",
  "language-server-protocol",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Text Editors :: Integrated Development Environments (IDE)",
  "Topic :: Utilities",
  "Typing :: Typed",
]
include = ["README.md"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
jedi = "^0.18.0"
pygls = "^0.11.1"
pydantic = "^1.7"
docstring-to-markdown = "0.*"
importlib-metadata = { version = "^3.10.0", python = "~3.7" }

[tool.poetry.dev-dependencies]
pre-commit = "^2.11"
tox = "^3.13"
pytest = "^6.2"
tox-asdf = "^0.1.0"
toml-sort = "^0.19.0"
isort = "^5.7.0"
pylint = "^2.6.0"
mypy = "^0.902"
black = "^22.3.0"
PyHamcrest = "^2.0.2"
python-jsonrpc-server = "^0.4.0"
pytest-cov = "^2.11.1"
docformatter = "^1.4"

[tool.poetry.scripts]
jedi-language-server = 'jedi_language_server.cli:cli'

[tool.poetry.urls]
Changelog = "https://github.com/pappasam/jedi-language-server/blob/main/CHANGELOG.md"
Issues = "https://github.com/pappasam/jedi-language-server/issues"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,38,39,310}{,-cov}
isolated_build = true
skipsdist = true
[testenv]
platform = linux|darwin
whitelist_externals = poetry
skip_install = true
commands =
  poetry install

  !cov: poetry run black --check --diff jedi_language_server tests
  !cov: poetry run docformatter --check --recursive jedi_language_server tests
  !cov: poetry run isort --check jedi_language_server tests

  !cov: poetry run mypy jedi_language_server
  !cov: poetry run pylint jedi_language_server tests
  !cov: poetry run pytest tests

  cov: poetry run pytest --cov=jedi_language_server --cov-report=term-missing tests
"""
