# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61\x63heclient.proto\x12\x0c\x63\x61\x63he_client\" \n\x0b_GetRequest\x12\x11\n\tcache_key\x18\x01 \x01(\x0c\"_\n\x0c_GetResponse\x12*\n\x06result\x18\x01 \x01(\x0e\x32\x1a.cache_client.ECacheResult\x12\x12\n\ncache_body\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"#\n\x0e_DeleteRequest\x12\x11\n\tcache_key\x18\x01 \x01(\x0c\"\x11\n\x0f_DeleteResponse\"N\n\x0b_SetRequest\x12\x11\n\tcache_key\x18\x01 \x01(\x0c\x12\x12\n\ncache_body\x18\x02 \x01(\x0c\x12\x18\n\x10ttl_milliseconds\x18\x03 \x01(\x04\"K\n\x0c_SetResponse\x12*\n\x06result\x18\x01 \x01(\x0e\x32\x1a.cache_client.ECacheResult\x12\x0f\n\x07message\x18\x02 \x01(\t*<\n\x0c\x45\x43\x61\x63heResult\x12\x0b\n\x07Invalid\x10\x00\x12\x06\n\x02Ok\x10\x01\x12\x07\n\x03Hit\x10\x02\x12\x08\n\x04Miss\x10\x03\"\x04\x08\x04\x10\x06\x32\xce\x01\n\x03Scs\x12>\n\x03Get\x12\x19.cache_client._GetRequest\x1a\x1a.cache_client._GetResponse\"\x00\x12>\n\x03Set\x12\x19.cache_client._SetRequest\x1a\x1a.cache_client._SetResponse\"\x00\x12G\n\x06\x44\x65lete\x12\x1c.cache_client._DeleteRequest\x1a\x1d.cache_client._DeleteResponse\"\x00\x42G\n\x11grpc.cache_clientP\x01Z0github.com/momentohq/client-sdk-go;client_sdk_gob\x06proto3')

_ECACHERESULT = DESCRIPTOR.enum_types_by_name['ECacheResult']
ECacheResult = enum_type_wrapper.EnumTypeWrapper(_ECACHERESULT)
Invalid = 0
Ok = 1
Hit = 2
Miss = 3


__GETREQUEST = DESCRIPTOR.message_types_by_name['_GetRequest']
__GETRESPONSE = DESCRIPTOR.message_types_by_name['_GetResponse']
__DELETEREQUEST = DESCRIPTOR.message_types_by_name['_DeleteRequest']
__DELETERESPONSE = DESCRIPTOR.message_types_by_name['_DeleteResponse']
__SETREQUEST = DESCRIPTOR.message_types_by_name['_SetRequest']
__SETRESPONSE = DESCRIPTOR.message_types_by_name['_SetResponse']
_GetRequest = _reflection.GeneratedProtocolMessageType('_GetRequest', (_message.Message,), {
  'DESCRIPTOR' : __GETREQUEST,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._GetRequest)
  })
_sym_db.RegisterMessage(_GetRequest)

_GetResponse = _reflection.GeneratedProtocolMessageType('_GetResponse', (_message.Message,), {
  'DESCRIPTOR' : __GETRESPONSE,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._GetResponse)
  })
_sym_db.RegisterMessage(_GetResponse)

_DeleteRequest = _reflection.GeneratedProtocolMessageType('_DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : __DELETEREQUEST,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._DeleteRequest)
  })
_sym_db.RegisterMessage(_DeleteRequest)

_DeleteResponse = _reflection.GeneratedProtocolMessageType('_DeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : __DELETERESPONSE,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._DeleteResponse)
  })
_sym_db.RegisterMessage(_DeleteResponse)

_SetRequest = _reflection.GeneratedProtocolMessageType('_SetRequest', (_message.Message,), {
  'DESCRIPTOR' : __SETREQUEST,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._SetRequest)
  })
_sym_db.RegisterMessage(_SetRequest)

_SetResponse = _reflection.GeneratedProtocolMessageType('_SetResponse', (_message.Message,), {
  'DESCRIPTOR' : __SETRESPONSE,
  '__module__' : 'cacheclient_pb2'
  # @@protoc_insertion_point(class_scope:cache_client._SetResponse)
  })
_sym_db.RegisterMessage(_SetResponse)

_SCS = DESCRIPTOR.services_by_name['Scs']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021grpc.cache_clientP\001Z0github.com/momentohq/client-sdk-go;client_sdk_go'
  _ECACHERESULT._serialized_start=379
  _ECACHERESULT._serialized_end=439
  __GETREQUEST._serialized_start=35
  __GETREQUEST._serialized_end=67
  __GETRESPONSE._serialized_start=69
  __GETRESPONSE._serialized_end=164
  __DELETEREQUEST._serialized_start=166
  __DELETEREQUEST._serialized_end=201
  __DELETERESPONSE._serialized_start=203
  __DELETERESPONSE._serialized_end=220
  __SETREQUEST._serialized_start=222
  __SETREQUEST._serialized_end=300
  __SETRESPONSE._serialized_start=302
  __SETRESPONSE._serialized_end=377
  _SCS._serialized_start=442
  _SCS._serialized_end=648
# @@protoc_insertion_point(module_scope)
