[tool.poetry]
name = "pyrfkit"
version = "1.1.0"
description = "Python RF Kit built on scikit-rf."
authors = ["Adam Page <adam.page@samtec.com>"]
homepage = "https://bitbucket.org/samteccmd/pyrfkit"
repository = "https://bitbucket.org/samteccmd/pyrfkit"
packages = [ { include = "rfkit" }]

[tool.taskipy.tasks]
lint =  "pylint --rcfile .pylintrc rfkit"
test = "pytest tests/"

[tool.poetry.dependencies]
python = "^3.8"
scikit-rf = "^0.22.0"
numpy = "*"
scipy = "*"
pandas = "*"
h5py = "*"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
pytest = "^6.2.1"
pep8 = "^1.7.1"
pylint = "^2.6.0"
autopep8 = "^1.5.4"
taskipy = "^1.6.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
