[tool.poetry]
name = "minimata"
version = "0.1.1"
description = "Minimata is a minimalist state-machine implementation."
documentation= "https://github.com/nicoolas25/minimata"
repository= "https://github.com/nicoolas25/minimata"
authors = ["Nicolas Zermati <nicoolas25@gmail.com>"]
readme = "README.md"
packages = [
  { include = "minimata" },
  { include = "README.md" },
  { include = "LICENSE" },
]

[tool.poetry.dependencies]
python = "^3.8"
graphviz = "^0.20"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.942"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
