[tool.poetry]
name = "pyliveatc"
version = "0.1.0"
description = ""
authors = ["ruyyi0323 <ruyyi0323@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.4.2"
numpy = "^1.22.3"
click = "^8.1.2"
lxml = "^4.8.0"
loguru = "^0.6.0"
pydantic = "^1.9.0"
ffmpeg-python = "^0.2.0"
scipy = "^1.8.0"
sounddevice = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
