
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-27T15:19:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "24641ebba396f3e69c5cdc42f0b5cc2ca052fcea",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
