[tool.poetry]
name = "ethoscopy"
version = "0.1.1"
description = "A python based toolkit to download and anlyse data from the Ethoscope hardware system."
authors = ["Blackhurst Laurence <l.blackhurst19@imperial.ac.uk>"]
license = "GNU"
readme = "readme.md"

[tool.poetry.dependencies]
python = "~3.10"
pandas = "^1.4.2"
numpy = "^1.22.3"
tabulate = "^0.8.9"
plotly = "^5.7.0"
scipy = "^1.8.0"
hmmlearn = "^0.2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
