name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir black isort pytest
# consider flit install if we want to test the code itself
      - name: Lint Code
        run: |
          python -m black --check --diff . --exclude="docs" --exclude="docs_src"
          python -m isort --check --diff . --skip "docs" --skip "docs_src"
# Can't run test right now because our tests are not standalone and assume servers exist
# TODO: Also issue where dev dependencies are not installed
#      - name: Test Code
#        run: |
#          pytest
