[package]
name = "evg-task-profiler-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "evg_task_profiler_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }
chrono = "0.4"
lazy_static = "1.4"
regex = "1"
