[tool.poetry]
name = "ptext"
version = "1.1.0"
description = "Makes printing effect (ptext.printing(\"your text\", delay_not_necessary))"
authors = ["TimoXBeR <bertim20102@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
