[tool.poetry]
name = "pytest-kexi"
version = "0.10.1"
description = ""
authors = ["Kei Nakayama <kei.of.nakayama@gmail.com>"]
packages = [{ include = "src/pytest_kexi" }]
[tool.poetry.plugins.pytest11]
pytest-kexi = "pytest_kexi.helper"
[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
#pytest-kexi = {path = "src", develop=true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
