[tool.poetry]
name = "torncoder"
version = "0.1.0"
description = "Basic tornado-based python utilities."
authors = ["Aaron Gibson <eulersidcrisis@yahoo.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.8,<4"
aiofile = "^3.7.4"
tornado = "^6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
