version: '3.7'

services:

  car.tftp:
    container_name: car.tftp
    image: ghcr.io/qtc-de/container-arsenal/tftp:1.0.0
    build: .
    environment:
      LISTEN_PORT: ${car_tftp_port}
      LOCAL_UID: ${car_local_uid}
    volumes:
      - ${car_tftp_folder}:/ftp
      - ./scripts/start.sh:/scripts/start.sh
      - ./config/mapfile:/config/mapfile
    network_mode: "host"
