name: "CCVFighter"
type: "Linear_Quadratic"
Q_gain:
    - 1.0
    - 1.0
    - 1.0
R_gain:
    - 1.0
    - 1.0
dt: 0.01
state_dim: 3
action_dim: 2
max_t: 2.0
bounds:
    state_unit:
        - "deg2rad"
        - "deg2rad"
        - "deg2rad"
    action_unit:
        - "deg2rad"
        - "deg2rad"
    state_min:
        - -10.0
        - -30.0
        - -10.0
    state_max:
        - 10.0
        - 30.0
        - 10.0
    action_min:
        - -25.0
        - -20.0
    action_max:
        - 25.0
        - 20.0
normalisation:
    x: null
    u: null
