name: "F16LongLinear3Dim"
type: "Linear_Quadratic"
Q_gain:
    - 1.0
    - 1.0
    - 0.01
R_gain:
    - 0.01
dt: 0.01
state_dim: 3
action_dim: 1
max_t: 10.0
bounds:
    state_unit:
        - "deg2rad"
        - "deg2rad"
        - null
    action_unit:
        - null
    state_min:
        - -5.0
        - -5.0
        - -5.0
    state_max:
        - 5.0
        - 5.0
        - 5.0
    action_min:
        - -5.0
    action_max:
        - 5.0
normalisation:
    x:
        - 0.0175  # \approx \pi/180
        - 0.0175  # \approx \pi/180
        - 1.0
    u: null
