name: "F16LongLinear"
type: "Linear_Quadratic"
Q_gain:
    - 0.005
    - 0.005
    - 0.005
    - 0.005
R_gain:
    - 0.01
dt: 0.1
state_dim: 4
action_dim: 1
max_t: 5.0
bounds:
    state_unit:
        - null
        - "deg2rad"
        - "deg2rad"
        - "deg2rad"
    action_unit:
        - null
    state_min:
        - -5.0
        - -5.0
        - -5.0
        - -5.0
    state_max:
        - 5.0
        - 5.0
        - 5.0
        - 5.0
    action_min:
        - -5.0
    action_max:
        - 5.0
normalisation:
    x: null
    u: null
