name: pre-commit

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --files ${{ steps.file_changes.outputs.files}}
