[tool.poetry]
name = "solace"
version = "0.1.14"
description = "A Modern Framework for Building Python Web Apps"
authors = ["Dan Sikes <dansikes7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
starlette = "^0.19.0"
typer = {extras = ["all"], version = "^0.4.1"}
pydantic = "^1.9.0"
loguru = "^0.6.0"
python-dotenv = "^0.20.0"
Jinja2 = "^3.1.1"
arrow = "^1.2.2"
uvicorn = "^0.17.6"
pyaml = "^21.10.1"
PyInquirer = "^1.0.3"
watchgod = "^0.8.2"
Cerberus = "^1.3.4"
pygogo = "^1.3.0"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
solace = 'solace.cli:cli'
