
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T17:23:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b7dabdcca7c4a4b2d0a2598dc194df3f80172e2",
 "version": "v1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
