[tool.poetry]
name = "pytest-kexi"
version = "0.7.40"
description = ""
authors = ["Kei Nakayama <kei.of.nakayama@gmail.com>"]

[tool.poetry.plugins.pytest11]
pytest-kexi = "pytest_kexi.helper"


[tool.poetry.dependencies]
python = "^3.10"

logzero = "^1.7.0"



[tool.poetry.dev-dependencies]
twine = "^4.0.0"
pytest = "^7.1.2"
toml = "^0.10.2"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

