[tool.poetry]
name = "dwhgen"
version = "0.1.1"
description = "generating schema YAML and models for source system interfaces and PSA historization"
authors = ["Torsten Glunde <torsten@glunde.de>"]

[tool.poetry.dependencies]
python = "^3.9"
dbt = "^0.21.1"
SQLAlchemy = "1.3.23"
sqlalchemy-exasol = "^2.2.0"
pysqlite3 = "^0.4.6"
sqlalchemy-pysqlite3 = "^0.0.4"
pydantic = "^1.8.2"
python-dotenv = "^0.19.0"
ibm-db-sa = "^0.3.7"
pyexasol = "^0.21.1"
pymssql = "^2.2.2"
yamlreader = "^3.0.4"
sqlfluff = "^0.8.1"
dbt-exasol = "^1.0.3"
HiYaPyCo = "^0.4.16"
markupsafe = "2.0.1"

[tool.poetry.dev-dependencies]
pylint = "^2.13.3"

[build-system]
