[tool.poetry]
name = "costack_cli"
version = "0.2.3"
description = ""
authors = ["perseus.yang <ry82@cornell.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
boto3 = "^1.20.23"
awscli = "^1.22.23"
pyOpenSSL = "^22.0.0"
inquirer = "^2.9.1"
halo = "^0.0.31"
emoji = "^1.7.0"

[tool.poetry.scripts]
costack = "costack_cli.main:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
