
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-28T12:03:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8cc1892ac67053cfca4ded0d7caf67802fb0281",
 "version": "2666"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
