[tool.poetry]
name = "taxus"
version = "0.0" # this is automatically filled based on __init__.py
description = "Gaussian Process models for transcriptome data"
authors = ["Rens Holmer"]
readme = "README.md"
license = "MIT"
classifiers = [
            'Development Status :: 3 - Alpha',
            'Natural Language :: English',
            'Operating System :: MacOS',
            'Operating System :: Microsoft :: Windows',
            'Operating System :: POSIX',
            'Operating System :: Unix',
            'Intended Audience :: Developers',
            'Intended Audience :: Science/Research',
            'Topic :: Scientific/Engineering :: Bio-Informatics',
            'Topic :: Utilities'
        ]
repository = 'https://github.com/holmrenser/taxus'

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.1"
numpy = "^1.22.3"
torch = "^1.11.0"
gpytorch = "^1.6.0"
patsy = "^0.5.2"
tqdm = "^4.63.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^4.0.1"
pytest = "^7.0"
black = "^22.1.0"
coverage = {extras = ["toml"], version = "^6.3.1"}
coveralls = "^3.3.1"
mkdocs = "^1.2.3"
mkapi = "^1.0.14"
mkdocs-material = "^8.1.11"
mkdocs-jupyter = "^0.20.0"
mkdocstrings = "^0.18.0"
jupyter = "^1.0.0"
ipykernel = "^6.9.1"
patchworklib = "^0.4.0"

[tool.poetry-version-plugin]
source = "init"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--verbose --doctest-modules"
testpaths = ["taxus","tests"]
python_classes = "*Tests"
python_functions = "test*"
python_files = "*tests.py"

[tool.coverage.run]
branch = true
command_line = "-m pytest"

[tool.coverage.report]
omit = ["tests/*", "*__init__.py"]
