# encoding: utf-8
__version__ = '0.1'
__title__ = 'gitlab-branch'
__description__ = 'Manage branch for gitlab project'
__url__ = 'https://github.com/joelee2012/gitlab-branch'
__author__ = 'Joe Lee'
__author_email__ = 'lj_2005@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2022 Joe Lee'
__documentation__ = 'https://gitlab-branch.readthedocs.io'
