
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-24T13:06:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c19ac79965eb4b3b11f432fd46efc620aa28f72f",
 "version": "2.6.4.dev20220429"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
