
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-27T04:45:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1220954d4f203f28774be1958c21743ac6588567",
 "version": "0.0.77.post0.dev494"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
