
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T21:03:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4309a116e8d2e9d1a683b8005ddfc2cb92e044e8",
 "version": "0.0.77.post0.dev48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
