
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-27T14:22:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad3af34e35da20e1f46c4bf697fe48012b076dcb",
 "version": "2664"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
