[tool.poetry]
name = "baseten_scaffolding"
version = "0.0.19"
description = ""
authors = ["Alex Gillmor <alex@baseten.co>"]
include = ["*.txt", "*.Dockerfile", "*.md"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.18"
msgpack = "1.0.2"
msgpack-numpy = "0.4.7.1"
packaging = "20.9"
python-json-logger = "2.0.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
torch = "^1.9.0"
ipython = "^7.16"
pytest = "6.2.4"
tensorflow = "^2.4.0"
transformers = "^4.11.2"
scikit-learn = "1.0.2"
pandas = "1.1.5"
tensorflow-hub = "^0.12.0"
kfserving = "^0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
