[tool.poetry]
name = "bytestory"
version = "0.1.0"
description = "Unpacking from bytes and packing into bytes, with an object interface."
readme = "README.md"
authors = ["Xu Siyuan <inqb@protonmail.com>"]
repository = "https://github.com/no1xsyzy/bytestory"
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

