[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "docker-evolve"
version = "0.1.0"
description = ""
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
packages = [{ include = "docker_evolve", from = "src" }]
classifiers = []
keywords = []

[tool.poetry.urls]
# "Bug Tracker" = ""
# Documentation = ""
# Homepage = ""
# Repository = ""

[tool.poetry.dependencies]
python = "^3.7"
docker-py = "^1.10.6"

[tool.poetry.dev-dependencies]
mypy = "*"
pytest = "*"

[tool.poetry.scripts]
docker-evolve = "docker_evolve.__main__:main"

[tool.slap]
typed = true

[tool.slap.test]
check = "slap check"
mypy = "MYPYPATH=src mypy src/ --namespace-packages --explicit-package-bases"
pytest = "pytest test/ -vv"

[tool.mypy]
pretty = true
namespace_packages = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
show_error_context = true
show_error_codes = true
