
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T00:45:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7605518da7c1dfd6d0310c3c15198bea08bb37e",
 "version": "0.0.77.post0.dev23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
