
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T16:09:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3028f91ac0e9713decb5e9d39a40851111a8fabd",
 "version": "0.1.78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
