[tool.poetry]
name = "aiogram_utils"
version = "0.1.1"
description = "Misc utils for aiogram"
authors = ["levch <levchenko.d.a1998@gmail.com>"]
readme = 'README.md'
repository = 'https://github.com/LDmitriy7/aiogram_utils'

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.20"
mongoengine = "^0.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
