[tool.poetry]
name = "raptor_functions"
version = "0.2.65"
description = "raptor functions"
repository = "https://github.com/Bryant-Dental/raptor_functions.git"
authors = ["Daniel Fiuza, Ibrahim Animashaun"]



[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py36', 'py37', 'py38']
