[tool.poetry]
name = "apologiesserver"
version = "0.1.21"
description = "Websocket server to interactively play the Apologies game"
authors = ["Kenneth J. Pronovici <pronovic@ieee.org>"]
license = "Apache-2.0"
readme = "PyPI.md"
homepage = "https://pypi.org/project/apologiesserver/"
repository = "https://github.com/pronovic/apologies-server"
include = [
   { path = 'Changelog', format = 'sdist' },
   { path = 'LICENSE', format = 'sdist' },
   { path = 'README.md', format = 'sdist' },
   { path = 'docs', format = 'sdist' },
   { path = 'tests', format = 'sdist' },
]
packages = [ { include = "apologiesserver", from = "src" } ]
classifiers=[
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: Apache Software License",
   "Operating System :: OS Independent",
   "Environment :: Console",
   "Intended Audience :: Developers",
   "Natural Language :: English",
   "Topic :: Games/Entertainment :: Board Games",
]

[tool.poetry.scripts]
apologies-server = 'apologiesserver.scripts:server'

[tool.poetry.dependencies]
python = ">=3.7,<4"
apologies = "^0.1.34"
websockets = "^9.1"
asyncio-periodic = "^2019.2"
ordered-set = "^4.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-testdox = "^2.0.1"
coverage = "^6.1.1"
tox = "^3.24.4"
pylint = "^2.11.1"
sphinx = "^4.3"
toml = "^0.10.2"
pre-commit = "^2.15.0"
black = "^21.10b0"
mypy = "^0.910"
isort = "^5.10.0"
sphinx-autoapi = "^1.8.4"
pytest-asyncio = "^0.16.0"
asynctest = "^0.13.0"
ordered-set-stubs = "^0.1.3"
coveralls = "^3.3.1"

[tool.black]
line-length = 132
target-version = ['py37', 'py38']
include = '(src\/scripts\/.*$|\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
  | docs
  | notes
)/
'''

[tool.isort]
profile = "black"
line_length = 132
skip_glob = [ "docs", "notes" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
