[tool.poetry]
name = "lawsql-cases-raw"
version = "0.0.10"
description = "Get decision data from .html and yaml files; updates local database with field lookups."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]

[tool.poetry.dependencies]
python = "^3.9"
citation-decision = "^0.0.3"
lawsql-cases-justices = "^0.0.4"
Unidecode = "^1.3.0"
sqlite-utils = "^3.26"
httpx = "^0.22.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
mypy = "^0.942"
black = "^22.3.0"
isort = "^5.10"
pre-commit = "^2.18"
ipykernel = "^6.13"
tqdm = "^4.64"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-modules --cov=lawsql_cases_raw tests/"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.1.12"]
build-backend = "poetry.core.masonry.api"
