# Generated by Django 3.2.13 on 2022-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0020_alter_geolocation_isp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipfingerprint',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='ip_fingerprints',
            field=models.ManyToManyField(to='djspoofer.IPFingerprint'),
        ),
    ]
