
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-26T02:21:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1faea9335bbc3268d9fce52992426a48014c80ad",
 "version": "0.0.77.post0.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
