[tool.poetry]
name = "djangodollar"
version = "0.2.0"
description = "A simple package for working with dollar amounts in Django."
authors = ["Ethan Corey <ethanscorey@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
