[tool.poetry]
name = "nii-info"
version = "1.0.1"
description = "Display NIfTI image information in a tabular format"
authors = ["Andrew Ross <andrew.ross.mail@gmail.com>"]
license = "MIT"

readme = "README.md"

keywords = ["nifti", "neuroimaging", "neuro", "cli"]

homepage = "https://github.com/andrewrosss/nii-info"
repository = "https://github.com/andrewrosss/nii-info"
documentation = "https://github.com/andrewrosss/nii-info"

classifiers = [
    "Programming Language :: Python :: 3.0",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8"
nibabel = "^3.0.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pylint = "^2.13.7"
reorder-python-imports = "^3.1.0"
bump2version = "^1.0.1"
pre-commit = "^2.18.1"
pytest = "^7.1.2"

[tool.poetry.scripts]
nii = 'nii_info:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
