name: "plse"
i_max: 20
T: 1.0
node_list:
    - 64
    - 64
    - 64
act:
    name: "leakyrelu"
trainable: True
train:
    method: "pcql-penalty"
    weight_origin: 1.0e+3
    weight_nonneg: 1.0e+3
    grad_max_norm: 1.0e-1
    lr: 1.0e-3
