[tool.poetry]
name = "sql-models-infomoto"
version = "0.4.0"
description = ""
authors = ["todotom <tomasdarioam@protonmail.com>"]
packages = [
    { include = "./sql_models/**/*.py" },
]

[tool.poetry.dependencies]
python = "3.10.4"
sqlmodel = "0.0.6"
camel-model = "0.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
