
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T04:55:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28bff94bd1b243188fa1d7bd714059d1f085428d",
 "version": "1.16.0.post.dev412"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
