[tool.poetry]
name = "qzlt"
version = "0.1.0"
description = "A Quizlet clone for the command line"
authors = ["Calvin Cheng <calvin.cc.cheng@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
quiz = "qzlt.main:app"
test = "scripts:run_tests"

[tool.poetry.dependencies]
python = "^3.6.2"
typer = {extras = ["all"], version = "^0.4.1"}

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
