[project]
name = "mina-build"
version = "0.1.7"
description = "build backend for Mina Package Structure"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = [
    "pdm-pep517>=0.12.3",
]
requires-python = ">=3.9"
readme = "README.build.md"
mina-package = "backend"
includes = [
    "mina/backend",
]

[project.license]
text = "MIT"

[project.optional-dependencies]

[project.entry-points]

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "isort>=5.10.1",
    "devtools>=0.8.0",
]

[tool.mina]
enabled = true

[tool.mina.packages.backend]
name = "mina-build"
version = "0.1.7"
description = "build backend for Mina Package Structure"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = [
    "pdm-pep517",
]
requires-python = ">=3.9"
readme = "README.build.md"
includes = [
    "mina/backend",
]

[tool.mina.packages.backend.license]
text = "MIT"

[tool.mina.packages.backend.entry-points]

[build-system]
requires = [
    "mina-build>=0.1.6",
    "setuptools",
]
backend-path = "."
build-backend = "mina.backend"
