[build-system]
requires = ["poetry"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "APAV"
version = "1.2.2"
description = "A Python library for Atom Probe Tomography analysis"
readme = "README.md"
authors = ["Jesse Smith <jesseds@protonmail.ch>"]
homepage = "https://apav.readthedocs.io/en/latest/"
documentation = "https://apav.readthedocs.io/en/latest/"
repository = "https://gitlab.com/jesseds/apav"
keywords = ["atom probe", "tomography", "field evaporation", "data analysis", "materials science"]
classifiers = [
            "Programming Language :: Python :: 3",
            "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
            "Operating System :: OS Independent",
            "Intended Audience :: Science/Research",
            "Topic :: Scientific/Engineering :: Chemistry",
            "Topic :: Scientific/Engineering :: Visualization"
]

[tool.poetry.dependencies]
python = ">=3.6"
numpy = ">=1.17"
pyqtgraph = ">=0.11.0"
numba = "*"
lmfit = ">=1.0"
fast-histogram = "*"
tabulate = "*"
PyQt5 = ">=5.11"
periodictable = "*"
pytest = "*"
pytest-qt = ">=3"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints"]
