[tool.poetry]
name = "netbox-lists"
version = "2.1.1"
description = ""
authors = ["Devon Mar <devonm@mdmm.ca>"]

[tool.poetry.dependencies]
python = "^3.6.2"
netaddr = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8"
pynetbox = "^6.1.3"
requests = "^2.26.0"
isort = "^5.10.1"
black = "^22.1.0"
mypy = "^0.941"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
force_alphabetical_sort_within_sections = true

[mypy]
plugins = ["mypy_django_plugin.main"]

disallow_any_generics = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "rest_framework.*",
    "taggit.*",
    "django_filters",
    "netaddr.*",
    "drf_yasg.*",
    # NetBox
    "dcim.*",
    "ipam.*",
    "extras.*",
    "virtualization.*",
]
ignore_missing_imports = true
