# coding: utf-8

"""
    eHelply SDK - 1.1.74

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.74
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.inline_response2002 import InlineResponse2002


class TestInlineResponse2002(unittest.TestCase):
    """InlineResponse2002 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_InlineResponse2002(self):
        """Test InlineResponse2002"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2002()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
