# Generated by Django 3.2.12 on 2022-04-14 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0015_auto_20220414_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(max_length=32)),
                ('device_category', models.CharField(max_length=32)),
                ('os', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('screen_height', models.IntegerField()),
                ('screen_width', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('viewport_height', models.IntegerField()),
                ('viewport_width', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=24, max_digits=25)),
            ],
            options={
                'db_table': 'djspoofer_profile',
                'ordering': ['-weight'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['browser'], name='iprofile_browser'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['device_category'], name='iprofile_device_category'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['os'], name='iprofile_os'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['platform'], name='iprofile_platform'),
        ),
    ]
