[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "src/tests",
]

[tool.mypy]
exclude = "src/tests"
ignore_missing_imports = true
strict = true
