[tool.poetry]
name = "pytest-kexi"
version = "0.1.0"
description = ""
authors = ["Kei Nakayama <kei.of.nakayama@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
setuptools = "^62.1.0"
logzero = "^1.7.0"

[tool.poetry.dev-dependencies]
twine = "^4.0.0"
setuptools = "^62.1.0"
build = "^0.7.0"
pytest = "^7.1.2"


[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
