
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-28T17:37:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c7174d9c0e1485be2fa17341c3618bb45f2e28c",
 "version": "2667"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
