[tool.poetry]
name = "mpbroker"
version = "0.4.0"
description = "Media Player Broker"
license = "GPL-3.0-only"
authors = ["David Rader <sa@adercon.com>"]
maintainers = ["David Rader <sa@adercon.com>"]
readme = "README.md"
#homepage = ""
#repository = ""
keywords = ["media player", "broker", "player", "video", "smplayer", "vlc"]

#include = [""pyproject.toml]

[tool.poetry.scripts]
mpb = "mpbroker.main:app"

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.4.1"}
arrow = "^1.2.2"
pycouchdb = "^1.14.1"
pydantic = "^1.9.0"
requests = "^2.27.1"
rich = "^12.3.0"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[internal]
created = 2022-04-21
