# coding: utf-8

"""
    eHelply SDK - 1.1.73

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.73
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.body_attach_alarm_ticket_monitor_services_service_stages_stage_alarms_alarm_uuid_ticket_post import BodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost


class TestBodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost(unittest.TestCase):
    """BodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_BodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost(self):
        """Test BodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyAttachAlarmTicketMonitorServicesServiceStagesStageAlarmsAlarmUuidTicketPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
