[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "xls2txt"
authors = [{name = "erzo", email = "erzo@posteo.de"}]
dynamic = ["version", "description"]
requires-python = ">=3.6"
dependencies = [
	"xlrd",
]
classifiers = [
	"Environment :: Console",
	"License :: OSI Approved :: BSD License",
]

[project.urls]
Home = "https://gitlab.com/erzo/xls2txt"

[project.scripts]
xls2txt = "xls2txt.main:main"
