# Generated by Django 3.2.12 on 2022-04-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0017_auto_20220416_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='ip_fingerprint',
        ),
        migrations.RemoveField(
            model_name='ipfingerprint',
            name='ips',
        ),
        migrations.AddField(
            model_name='ipfingerprint',
            name='fingerprint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ip_fingerprints', to='djspoofer.fingerprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipfingerprint',
            name='ip',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
