# Generated by Django 3.2.13 on 2022-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0022_auto_20220428_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='isp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
