[tool.poetry]
name = "statsdict"
version = "0.1.7"
description = "Saveable dictionary of global stats"
authors = ["Joel Berendzen <joel@generisbio.com>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://github.com/hydrationdynamics/statsdict"
repository = "https://github.com/hydrationdynamics/statsdict"
documentation = "https://statsdict.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Chemistry"
]
keywords = [
    "statistics",
]

[tool.poetry.urls]
Changelog = "https://github.com/joelb123/statsdict/releases"

[tool.poetry.dependencies]
python = "^3.8.0,<4.0"
attrs = "*"
loguru = "*"
Pint = "*"
typer = "*"
uncertainties = "*"
tabulate = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = {extras = ["toml"], version = "*"}
safety = "*"
mypy = "*"
typeguard = "*"
xdoctest = {extras = ["colors"], version = "*"}
sphinx = "*"
sphinx-autobuild = "*"
pre-commit = "*"
flake8 = "*"
flake8-bandit = "*"
flake8-bugbear = "*"
flake8-docstrings = "*"
pep8-naming = "*"
darglint = "*"
reorder-python-imports = "*"
pre-commit-hooks = "*"
sphinx-rtd-theme = "*"
Pygments = "*"
pytest-datadir-mgr = "*"
isort = "*"
nox-poetry = "*"
pytest-cov = "*"
black = "*"
flake8-rst-docstrings = "*"
sphinx-click = "*"
icecream = "*"
types-tabulate = "*"
loguru-mypy = "*"

[tool.poetry.scripts]
statsdict = "statsdict.__main__:main"

[tool.black]
line-length = 79
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | \.mypy
  _cache
  | \.nox
  | \.idea
  | \.pytest-cache
  | _build
  | build
  | dist
  | tests/
)/
'''

[tool.coverage.paths]
source = ["statsdict", "*site-packages/statsdict"]

[tool.coverage.report]
show_missing = true
ignore_errors = true
exclude_lines = [
    "if self.debug:",
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
    ]

[tool.isort]
atomic = true
force_single_line = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
import_heading_stdlib = "standard library imports"
import_heading_thirdparty = "third-party imports"
import_heading_firstparty = "first-party imports"
import_heading_localfolder = "module imports"
known_standard_library = "pkg_resources"

[tool.poetry-dynamic-versioning]
enable = false
style = "semver"

[tool.pytest.ini_options]
addopts = "-x"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
