[tool.poetry]
name = "statworx_theme"
version = "0.4.2"
description = "A color theme for matplotlib using the offical statworx design"
authors = ["An Hoang <an.hoang@statworx.com>"]
readme = "README.md"
license = "MIT"
keywords = ["theme", "matplotlib", "plotting", "statworx"]
repository = "https://github.com/AnHo4ng/statworx-theme"
homepage = "https://statworx-theme.readthedocs.io/en/latest"
documentation = "https://statworx-theme.readthedocs.io/en/latest"

[tool.poetry.dependencies]
python = "~3.8.9"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pygments = "2.11.2"             # HACK: upgrading this leads to a bug with mkdocstrings
black = ">=22.3.0"
commitizen = ">=2.21.2"
darglint = ">=1.8.1"
flake8 = ">=4.0.1"
ipykernel = ">=6.9.2"
mkdocs = ">=1.3.0"
mkdocs-material = ">=8.2.8"
mkdocstrings = ">=0.18.1"
mkdocstrings-python = ">=0.6.6"
mkdocs-matplotlib = ">=0.8.3"
pre-commit = ">=2.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
