VERSION_YEAR = 2022
VERSION_MONTH = int('04')
VERSION_DAY = int('28')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('43')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202204281143
version_date = '2022/04/28 11:43'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
