[tool.poetry]
name = "taskick"
version = "0.1.6b0"
description = "Taskick is an event-driven Python library that automatically executes scripts or any commands."
authors = ["Atsuya Ide <atsuya.ide528@gmail.com>"]
repository = "https://github.com/atsuyaide/taskick"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
schedule = "^1.1.0"
watchdog = "^2.1.6"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"
flake8 = "^4.0.1"
black = "^22.1.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.black]
preview = true
exclude = "setup.py"
