
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T15:24:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2c449900ae8608fcf9951e9843021d91a618c0e",
 "version": "1.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
