[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "apio"
author = "Jesus Arroyo"
author-email = "jesus.jkhlg@gmail.com "
home-page = "https://github.com/FPGAwars/apio"
classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
        'Programming Language :: Python']
description-file = "README.md"
requires-python = ">=3.7"
requires = [
    'click==7.1.2',
    'semantic_version==2.9.0',
    'requests==2.27.1',
    'colorama==0.4.4',
    'pyserial==3.5',
    'wheel>=0.35.0,<1',
    'scons==4.2.0'
]

[tool.flit.sdist]
exclude = ["test-examples/"]

[tool.flit.metadata.requires-extra]
blackiceprog = ['blackiceprog==2.0.0']
litterbox = ['litterbox==0.2.2']
tinyfpgab = ['tinyfpgab==1.1.0']
tinyprog = ['tinyprog==1.0.21']
icefunprog = ['icefunprog==2.0.3']


[tool.flit.scripts]
apio = "apio.__main__:cli"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.pylint.messages_control]
disable = ["duplicate-code",
           "too-few-public-methods",
           "too-many-instance-attributes",
           "too-many-function-args",
           "broad-except",
           "too-many-arguments",
           "raise-missing-from",
           "dangerous-default-value",
           "missing-module-docstring",
           "missing-class-docstring",
           "missing-function-docstring",
           "too-many-locals",
           "too-many-nested-blocks",
           "too-many-branches",
           "too-many-statements",
           "invalid-name",
           "no-value-for-parameter",
           "no-member",
           "consider-using-with",
           "lost-exception",
           "eval-used",
           "redefined-builtin"]
