
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-25T11:29:14-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "95fec10de82d0c3c76cafa3b570fff85ba245a4a",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
