[tool.black]
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.pytest_cache
  | htmlcov
  | build
  | dist
  # Specific to this package
  | parallel_docker_build.egg-info
  | parallel-docker-build.egg-info
)/
'''
