# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hakan/a2t/pyroot/ui/exp_s3_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_S3WidgetBase(object):
    def setupUi(self, S3WidgetBase):
        S3WidgetBase.setObjectName("S3WidgetBase")
        S3WidgetBase.resize(712, 193)
        S3WidgetBase.setWindowTitle("")
        self.widget_vertical_Layout = QtWidgets.QVBoxLayout(S3WidgetBase)
        self.widget_vertical_Layout.setContentsMargins(20, 10, 5, 5)
        self.widget_vertical_Layout.setObjectName("widget_vertical_Layout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cloud_config_label = QtWidgets.QLabel(S3WidgetBase)
        self.cloud_config_label.setObjectName("cloud_config_label")
        self.gridLayout.addWidget(self.cloud_config_label, 0, 0, 1, 1)
        self.aws_secret_key_label = QtWidgets.QLabel(S3WidgetBase)
        self.aws_secret_key_label.setObjectName("aws_secret_key_label")
        self.gridLayout.addWidget(self.aws_secret_key_label, 2, 0, 1, 1)
        self.bucket_combo = QtWidgets.QComboBox(S3WidgetBase)
        self.bucket_combo.setEditable(True)
        self.bucket_combo.setCurrentText("")
        self.bucket_combo.setObjectName("bucket_combo")
        self.bucket_combo.addItem("")
        self.bucket_combo.setItemText(0, "")
        self.bucket_combo.addItem("")
        self.gridLayout.addWidget(self.bucket_combo, 3, 1, 1, 1)
        self.buket_label = QtWidgets.QLabel(S3WidgetBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buket_label.sizePolicy().hasHeightForWidth())
        self.buket_label.setSizePolicy(sizePolicy)
        self.buket_label.setText("Bucket:")
        self.buket_label.setObjectName("buket_label")
        self.gridLayout.addWidget(self.buket_label, 3, 0, 1, 1)
        self.aws_access_key_label = QtWidgets.QLabel(S3WidgetBase)
        self.aws_access_key_label.setObjectName("aws_access_key_label")
        self.gridLayout.addWidget(self.aws_access_key_label, 1, 0, 1, 1)
        self.cloud_config_combo = QtWidgets.QComboBox(S3WidgetBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloud_config_combo.sizePolicy().hasHeightForWidth())
        self.cloud_config_combo.setSizePolicy(sizePolicy)
        self.cloud_config_combo.setEditable(False)
        self.cloud_config_combo.setObjectName("cloud_config_combo")
        self.gridLayout.addWidget(self.cloud_config_combo, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.aws_secret_key_edit = QtWidgets.QLineEdit(S3WidgetBase)
        self.aws_secret_key_edit.setObjectName("aws_secret_key_edit")
        self.gridLayout.addWidget(self.aws_secret_key_edit, 2, 1, 1, 1)
        self.aws_access_key_edit = QtWidgets.QLineEdit(S3WidgetBase)
        self.aws_access_key_edit.setObjectName("aws_access_key_edit")
        self.gridLayout.addWidget(self.aws_access_key_edit, 1, 1, 1, 1)
        self.browse_bucket_button = QtWidgets.QPushButton(S3WidgetBase)
        self.browse_bucket_button.setObjectName("browse_bucket_button")
        self.gridLayout.addWidget(self.browse_bucket_button, 3, 2, 1, 1)
        self.widget_vertical_Layout.addLayout(self.gridLayout)

        self.retranslateUi(S3WidgetBase)
        QtCore.QMetaObject.connectSlotsByName(S3WidgetBase)

    def retranslateUi(self, S3WidgetBase):
        _translate = QtCore.QCoreApplication.translate
        self.cloud_config_label.setText(_translate("S3WidgetBase", "Cloud Config:"))
        self.aws_secret_key_label.setText(_translate("S3WidgetBase", "AWS Secret Key:"))
        self.bucket_combo.setItemText(1, _translate("S3WidgetBase", "Click load, or type bucket address"))
        self.aws_access_key_label.setText(_translate("S3WidgetBase", "AWS Access Key:"))
        self.browse_bucket_button.setText(_translate("S3WidgetBase", "Browse"))
