import numpy as np
from ._helpers import SpectralData as SpectralData
from typing import Any

whitepoints_cie1931: Any
whitepoints_cie1964: Any

def spectrum_to_xyz100(spectrum: SpectralData, observer: SpectralData, interpolation_type: str = ...) -> np.ndarray: ...
def compute_whitepoint(illuminant: SpectralData, observer: SpectralData) -> np.ndarray: ...
def planckian_radiator(temperature): ...
def a(interval_nm: int = ...): ...
def c(): ...
def d(nominal_temperature: float): ...
def d50(): ...
def d55(): ...
def d65(): ...
def d75(): ...
def e(): ...
def f2(): ...
def f7(): ...
def f11(): ...
