from ._helpers import SpectralData as SpectralData
from typing import Any

this_dir: Any

def cie_1931_2(stepsize: int = ...): ...
def cie_1964_10(stepsize: int = ...): ...
def wws_cie_1931_2(lmbda): ...
def wws_cie_1964_10(lmbda): ...
