[build-system]
requires = [
    "setuptools>=61",
]
build-backend = "setuptools.build_meta"

[project]
name = "bump_release"
version = "0.10.3"
authors = [
    { name = "François GUÉRIN", email = "fguerin@ville-tourcoing.fr" },
]
description = "Updates various version numbers for python projects"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
]
requires-python = ">=3.7"
dependencies = [
    "Click",
    "ruamel.yaml",
]

[project.urls]
Homepage = "https://github.com/frague59/bump-release"

[project.optional-dependencies]
toml = [
    "tomli",
    "tomli-w",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.scripts]
bump_release = "bump_release:bump_release"
bump-release = "bump_release:bump_release"

[tool.setuptools]
py-modules = [
    "bump_release",
]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false

[tool.black]
line-length = 120
target-version = [
    "py37",
    "py38",
    "py39",
]
exclude = "(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n    | migrations\n  )/\n)\n"

[tool.isort]
profile = "black"
line_length = 120
combine_as_imports = false
known_third_party = [
    "click",
    "ruamel.yaml",
]
known_first_party = [
    "bump_release",
]

[tool.pytest.ini_options]
addopts = [
    "--cov=bump_release",
    "--no-cov-on-fail",
    "--cov-config=.coveragerc",
]
testpaths = [
    "tests",
]
