name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow==2.7.0
          pip install statsmodels==0.12.1
          pip install pmdarima==1.8
      - name: Run tests with unittest
        run: python3 -m unittest discover       
