[build-system]
requires = [
    "setuptools >= 46.4.0",
]
build-backend = "setuptools.build_meta"

[tool.portray]
modules = ["isilon"]

[tool.portray.mkdocs.theme]
name = "material"
palette = {primary = "black", accent = "gray"}
